gnowledge/gstudio

gnowsys-ndf/gnowsys_ndf/ndf/views/rpc_resources.py
* ```rpc_resources.py```  --> filter added in query to fetch only ebooks, i.e zip files created_by  nroer_team
=> rpc method modified to fetch only nroer ebooks

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/group_dashboard.html
On scroll more events were not getting loaded on group dash board
Scroll Down to see more activities on the Group Dashboard
=> Fixgroupdashboard

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html, gnowsys-ndf/gnowsys_ndf/ndf/views/rpc_resources.py
* ```rpc_resources.py```  --> method modified to display metadata for ebook and resources in it as a collection.
* Now json return by this rpc method has format : 
**{ "[ ebook(zip/file) document ]" : [ ebooks resources(collection elements) ] }**
=> RPC method modified to display ebooks resources as its collection

gnowsys-ndf/gnowsys_ndf/ndf/views/rpc_resources.py
* Now collection_set elements of ebooks will also be processed to get the metadata i.e to fetch the metadata of pdf documents added inside the ebook document's (zip file) collection_set 
* Now the returned json has format : 
**{ "[ metadata of ebook uploaded(zip file) ]" : [ metadata of its collection elements ] }**
=> Bug resolved in rpc method to display metadata for ebook resources

gnowsys-ndf/gnowsys_ndf/ndf/views/rpc_resources.py
* Bug resolved in rpc method. 
* Now arranged ebook documents in proper format. along with their collection elements as per the requirement.
=> rpc method updated

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/announced_course_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
**Functionalities implemented:**
1) views/ajax_views.py
- ```get_colleges()``` modified:
- Additional parameter accepting required for following check: ```start_time``` and ```end_time```
- Check implemented:
-  For announcing course, returning list of only those college(s) in which course is not announced for given duration
2) templates/ndf/announced_course_create_edit.html
- Div added to list out college(s) in which course is already announced for given duration
- Accordingly added/changed required javascript & css code
=> MIS Update - Improvement for Course Announcement

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/data_review.html, gnowsys-ndf/gnowsys_ndf/ndf/views/data_review.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
**Appearance of page instances in data-review:**
- Previously it was not appearing in data-review. Which is enabled now.
- Also search in data-review shows page results.
**TEST:**
- Create page and try to find it in data-review.
- Try to search in data-review with that page's name.
=> Page instances now appeared in data-review

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/group_dashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/scrolldata.html
- *Onscroll* pagination is fixed.
- Fixed GAPP bar sliding behavior.
- Overlapping of listing on group's pic issue is resolved.
=> Group Dashboard CSS fix

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/batch_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/new_create_batch.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/student_enroll.html
Batches:
Earlier a Batch with any no. of students was able to create, even 0.
The check of minimum no. of students was placed on 'Save' button where batches with 0 members was not allowed to save.
Now, the check constraint is moved back to "Add Batch" button from "Save" button.
To Add a Batch, minimum 30 students are needed in that particular batch.
In last batch, where no students are further left, a batch can then have minimum of 25 students.
Also,
Alertmodals in student_enroll.html and new_create_batch.html have been modified with Yes/No buttons.
=> MIS updates on Batches

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/announced_course_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
- Previously becuase of checkbox selection, it was creating problems in listing college(s) for announcement. 
- As from selected list of course(s), there might be set of course(s) which were announced in different set of college(s); and in such case it is difficult to decide which college(s) to list down where course(s) (which might include course(s) not announced yet) needs to be  announce. 
- For other than foundation course(s), hence radio button-selection implemented which makes it easier to track whether given course is announced in given set of college(s) for given duration.
- Files modified:
1) ```views/ajax_views.py```
2) ```templates/ndf/announced_course_create_edit.html```
=> MIS Update [Bug-fix for Course Announcement (Domain Course)]

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/html_field_widget.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/organization_create_edit.html
Validations added are as follows:
Pincode will now accept min. and max 6 digits.
Mobile number will now accept min. and max 10 digits
Alternate/landline number number will now accept min. 8 and max 10 digits
Marks in Course Registration will now accept min. 2 and max 3 digits
Minutes in Course Structure will now accept min. 2 and max 3 digits
While editing, district dropdown was disabled by default. This is now enabled during editing.
Spaces are now allowed while entering Village, Taluka, Town/City in registrations. Only Letters and spaces can be entered.
=> MIS Validations

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/announced_course_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/views/organization.py
**What to test?**
- Register a college. Visit corresponding college group. Check while doing different registrations did you get data for fields such as caste, college, state, district and so on.
- In Course Announcement, try changing course duration and check whether university option gets reset or not.
**Modifications:**
1) **Populating data in newly created college group on creation of their respective college node (needed while registrations).**
- When a college is registered, previously, along with college's node a private group was also getting created.
- Now apart from that also populating required data into that group which is very much essential while doing different registration(s).
- File modified: ```views/organization.py```
2) **On change of course duration, resetting …
=> MIS Update

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/group_dashboard.html
- Repository default landing made to : "Curated Zone"
- Buttons on banner pic are removed.
=> NROER navigation and banner pic buttons

gnowsys-ndf/bower.json, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/approval_data_review.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/group_dashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/search_page.html
Please do following:
bower install datatables-plugins --save
Search results:
Even when there is no result, the number showed 1 for pages, now a label is displayed saying "No results found"
Modified: search_page.html
MIS:
student_approval data table is now made scrollable, properly formatted.
Modified: approval_data_review.html
=> Updates on search template & MIS student approval template

gnowsys-ndf/bower.json, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/group_dashboard.html
Please do:
bower install DataTables --savebower.json
The script links in group_dashboard.html are updated
=> bower install added

gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
- Previously, query was fired without checking argument is object-name (of data type string) or ObjectId.
- This bug is fixed. And checking has been added.
=> Bug in get_publish_policy() in ndf_tags.py file is resolved

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/Event_Attendance_check.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/Nussd_event_Schedule.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/event_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
run ATs.csv 
run property order reset to add created attribute to event node
check the flow of events
=> event status added to Specific events

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/Event_Attendance_check.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/Nussd_event_Schedule.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/event_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/event.py
Redirection to event app bug fixed
=> Event bug fix

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/student_enroll.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/batch.py, gnowsys-ndf/gnowsys_ndf/ndf/views/enrollment.py
Bug fixed in Enrollments, Approvals and Batches.
=> MIS Bug fixes

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/Nussd_event_Schedule.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
if a event is created by selecting one session for particular batch it wont appear next time for the same batch if all the session are scheduled for a particular module that module would stop listing in the drop down 
the same module session combination should appear for the next batch
=> Events module session combination

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/studentcourseenrollment_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/enrollment.py
Re-opening Enrollment bug fixed.
Editing StudentCourseEnrollment, if course type is Foundation, displays all announced courses in that SCE.
Updating StudentCourseEnrollment allows changing end_enroll date only if date is passed, else can update SCE without modifying dates, to reopen enrollments.
=> MIS updates

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/event_details.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
select all feature is blocked when attendance is blocked.
attendance done checkbox added.
if checked the attendance would be blocked 
redundant code removed
=> Attendance done check

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_course_structure.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/course.py
ndf/create_course_structure.html
While creating course sub-sections in course structure, the reveal modal to set properties will now ask the user to input values for Minimum and Maximum marks of that particular subsection, only if it is for 'Assessment'.
These marks can now be used in Events scheduled with the corresponding course subsection.
The Submit button on template is enabled only on the click of 'Done', inside the reveal modal, which ensures that the course has atleast one subsection.
/ndf/views/course.py
In saving, when a course subsection holds value for Min and Max marks, 2 new GAttributes will be created for these fields.
=> MIS Added minimum and maximum marks attributes for Course subsections

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/event_details.html, gnowsys-ndf/gnowsys_ndf/ndf/views/event.py
MIS : Earlier, for assessment in events, the min and max marks were considered of Course marks, entered in registration.
This has been changed now to consider the marks of the subsection(entered in course structure for every assessment subsection) for which the event session has been created.
=> Event assessment marks will consider course subsection's marks

gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
The error was - in checking with list and not with the node object. Which is now resolved.
=> Error in ndf_tags.get_publish_policy is resolved

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/settings.py
**The menu bar is modified as per discussion**:
- Top level menu will have: `Repository` | `Partners` | `Groups`
- Second level menu will have: `Curated Zone` | `eLibrary` | `eBooks` | `eCourses` | `Events`
- Only `Partners` will not have `Curated Zone` in the second level menu-bar.
- `Partners` and `Groups` among top-level menu will have drop-down listing of their groups.
- If any of their sub menu item is selected then:
- Top-level parent of selection will get highlighted.
- Also among sub menu, selected item will be highlighted.
- On click of `Partners` and `Groups`, listing of related groups appears as a card.
- Also second-level gapp bar is empty on list view.
- Also selected GAPP will be highlighted.
- As previous - `eBook`, `eCourses` and `Events` links are not active yet.
-- …
=> Re-modified two level menu-bar for NROER

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/scheduler_calender.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
day view is changed from agenda day to basic day view as it was creating confusing while viewing the event on the particular day of the same time events were overlapping on each other.
font size of event list in month and day view in creased
=> Calendar day view

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/settings.py
- Calling the same view from `groups.py` for `Partners` and `Groups`.
- Urls in `groups.py` reordered.
=> NROER: Menu issues for 'Partners' resolved

gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
Highlight on the list view is made enabled.
=> NROER: Highlight of selected-top-level item is enabled

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/data_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/mis_college_group.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/approval_data_review.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/student_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/student_list.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py, gnowsys-ndf/gnowsys_ndf/ndf/views/person.py
* Now enrollment code gets created on registration of every new student record
- New function defined: ```get_student_enrollment_code()```
- Enrollment Code is combination of following values: ```Code: (MH/SNG/15/xxxx)```
- 2-letters state code
- 3-letters college code
- 2-digits year of registration
- 4-digits Auto-generated No.
- Arguments:
- college_id: ObjectId of college's node
- node_id_to_ignore: ObjectId of the student node for which this function generates enrollment_code
- registration_date: Date of registration of student node for which this function generates enrollment_code
- college_group_id [Optional]: ObjectId of college's group node
- Returns:
- Newly created enrollment code for student node
- ```get_students()``` modified:
- Previously returning rendered template …
=> MIS Update (Student Enrollment Code)

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/event.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/event_list.html, gnowsys-ndf/gnowsys_ndf/ndf/views/event.py
List view of events is changed, two tabs name and status  and a legend on the left hand side to detail the information about the meaning of the colors  under status tab
=> Events list

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/data_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
* ```data_entry.py```:
- Skip parsing datetime.datetime fields if no value found.
* ```ajax_views.py``` modified:
- ```get_students()```: Student listing based on group set.
=> MIS Update (Minor changes)

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/data_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/sync_existing_documents.py, gnowsys-ndf/gnowsys_ndf/ndf/models.py
* Please run following command after taking this pull: **python manage.py sync_existing_documents**
* Check added in data_entry to identify unique student record
- making use of degree_name & degree_year fields for finding a given student record before creating/updating
* Structure updated for MetaType class
- Appended two fields: attribute_type_set and relation_type_set
=> MIS Update (data_entry updated)

gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
=> user profile pic upload

gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
* Bug fix: Now user can upload their profile pic.
=> Bug fix - Profile Pic Uploading

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/landing_page_beta.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/__init__.py, gnowsys-ndf/gnowsys_ndf/ndf/views/home.py
**Landing page made ready for NROER with other changes:** 
- New homepage url added and updated `view.home.homepage` 
- Non-essential imports commented out in `urls.__init__.py` file.
- New url `welcome` created for static-html-landing-page.
- 2 new `ndf_tags` added:
- `get_all_users_int_count` : To get all the users integer count.
- `get_all_file_int_count` : To get all the `PUBLIC` type `File` resources.
**Testing:**
- Do following additions in `local_settings.py` file to test this commit:
- `GSTUDIO_SITE_NAME = "nroer"`
- `GSTUDIO_SITE_LANDING_PAGE = "homepage"`
- Re/Start the project. Check if at start you will be redirected to landing page.
- Now try to login. After login you will be redirected to *user's dashboard*.
- Try to register new user. And after that activate the link and …
=> NROER: Landing page made ready

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/delete_pandora_video.py, gnowsys-ndf/gnowsys_ndf/ndf/views/e-library.py
**Minor changes**
* Pandora videos are deleted (since we dont have metadata for those videos)
* Script added for deleting pandora videos   -->  ```delete_pandora_ video.py```
* Querries modified for displaying resources in e-library.
**What to test**
* Go to e-library app and check all tabs where resources are listed out. Check whether listing is proper or not according to file type
```NOTE:``` Run python manage.py **delete_pandora_video.py**  which will delete all pandora videos
=> Resources are displayed in e-library according to file types  

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_statistics.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_course_structure.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/drawer_widget.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file_statistics.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/mis_base_list.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/uDashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/ajax-urls.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/course.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/course.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
/templates/ndf/create_course_structure.html
- Adding units to Course Subsections
- CSS changes 
/templatetags/ndf_tags.py
- Fetching drawer_widget using edit_drawer_widget
/ndf/views/ajax_views.py
- Ajax call to get resources
/ndf/views/course.py
- Saving resources in Course Sub section's collection_set
ndf/drawer_widget.html
- Prevent auro-recursive clicks of drawer buttons
ndf/uDashboard.html
- Reset footer in dashboard
=> MIS Adding Units to Course in structure

gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/registration_form.html
In the <code>registration_form.html</code> <i>agency_type</i> field made mandatory.
=> agency_type field made mandatory

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/themes_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/tag_browser.html
changes made in <code>tag_browser.html</code>
<code>hyper-link</code> is activated on <code>tag</code> selection.
Minor changes made in <code>themes_entry.py</code>
collection variable name changed to <code>node_colletion</code>
=> activate hyperlink on tags 

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/nroer_data_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/nroer_ebooks_entry.py
Updated nroer_data_entry script according to newer collection variables in models:
- Replaced `collection` queries with `node_collection`, `triple_collection` and `gridfs_collection`
=> Updated nroer_data_entry script according to newer collection variables in models

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/themes_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
Changes made in:
1. <code>str_to_dict</code> tag: if <i>attribute_set</i> has list value it shows in comma separated form in info-box.
2. nroer_team added in contributors field in <code>themes_entry.py</code> script
=> minor correction in str_to_dict tag

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/discussion.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html
**Discussion feature enabled for Page app:**
- Previously, **Discussion** feature was enabled only for `File` / `E-Library` apps.
- Now it's enabled for `Page` app.
- On addition/deletion of discussion thread/replies, tab text gets updated according to count of replies.
=> Discussion feature enabled for Page app

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/convert_mid_size_images.py, gnowsys-ndf/gnowsys_ndf/ndf/views/file.py, gnowsys-ndf/gnowsys_ndf/ndf/views/imageDashboard.py
**Convert mid size images script updated:**
- Now script will remove and re-insert image thumbnails and mid-size-image
- Arguments for getting thumbnails and mid-size image has been updated in `file.py` and `imageDashboard.py`
=> Convert mid size images script updated

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/nroer_data_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/nroer_ebooks_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
**NROER data entry scripts has been updated to accomodate recent changes in models:**
- Following scripts has been updated:
- `nroer_data_entry`
- `nroer_ebooks_entry`
- Also script is well indented.
=> NROER data entry scripts has been updated to accomodate recent changes in models

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/uDashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/views/search_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
query modified in order to search query string including spaces
the search result would contain the latest created or updated results first
=> Search View modified

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/uDashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
bug:-
previously when we redirect to the user dashboard , the content of the dashboard was the content of the logged in user.
the bug is fixed, now it would show the content of the requested user.
the cards on the user dashboard used to break the link when we include a tag .
the issue is fixed now cards on the dashboard also has links for tags
task will not be listed in the activity panel of the user  when viewing the user dashboards public i.e when someone is else logged in and viewing someone else dashboard or viewing a dashboard without logged in
=> Redirection to the user dash board on click of user fixed

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/group_dashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/groupdashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
Group profile pic edit allowed, only for authorized users
- If logged in user is member/admin/creator of that group then only he/she can edit the group-profile pic.
=> Group profile pic edit allowed, only for authorized users

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_thread.html
- Current code has JS error while creating thread.
- After taking the pull, try to create a thread. Thread should get created.
=> Error while creating thread is resolved

gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
placed get_time_Decorator on ndf tags
=> Get time decorator ndf

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/partners_details.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/settings.py
1. As per recent changes in models.py collection variable name changed to <code>node_collection</code>
2. check implemented for <code>group</code> if specific does not exist then method creates the group.
3. <code>nroer_team</code>added in author_set. If user with nroer_team does not exist then by importing <code>create_user_nroer_team()</code> method user created.
Run following command:
<code>python manage.py partners_details</code>
=> partners_details.py script modified.

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/collection_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html
* Rating feature is only kept for resources now(Page and File)
* Minor changes on themes card view, according to app name,  shifted text "Themes" to left top panel
* "In Other languages"  option is temporarily commented to avoid confusion in topic page, since we are listing resources in other languages in a separate tab 
* Topic node in breadcrumbs list is made unclickable
=> Minor issues resolved 

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_metastudio_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_nroer_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/landing_page_nroer.html
- JS modified to show slider banners in landing page.
- `.workplace` SCSS modified and watermark position re-arranged for nroer.
=> NROER Changes: Landing page and watermark.

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/repository.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/__init__.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py, gnowsys-ndf/gnowsys_ndf/settings.py
- Now on click of NROER's Repository, repository page created. Which will have card view of all the apps in repository.
- `E-Books` app kept at last.
- In `ndf_tags`, redundant code for detecting group_id or group_name replaced with one line function defined in methods.py
**TO-DO**
- `python manage.py filldb`
=> NROER: Added flow for repository page rendering and other small issues.

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/themes_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/repository.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html, gnowsys-ndf/gnowsys_ndf/ndf/views/imageDashboard.py, gnowsys-ndf/gnowsys_ndf/ndf/views/videoDashboard.py
*  ```themes_entry.py```  --> script updated for creating theme map, also updated collection_set and prior_node relation within theme map
* Url updated for image and video url redirection to topic with breadcrumbs within the context of topic.
=> Script updated for creating theme map

gnowsys-ndf/gnowsys_ndf/benchmarker/templates/reports.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/uDashboard.html
when not logged in their was a text places "you do not have rights to upload a picture pleas login",
but when someone visits someones else dashboard this message is not appropriate he  should be either shown the uploaded image by that user or the blank picture indicating no image is uploaded.
reduced the shadows added to the no picture image,
when we are not logged in we would now see the image uploaded or no image picture 
with no upload button.
=> Userdashboard fix

gnowsys-ndf/gnowsys_ndf/benchmarker/templates/reports.html
when i hit the metastudio site to view the benchmark, the enormous amount of  drawing table because of data killed the browser several time so i added pagination to the reports page.
added foundation link to the reports.html
=> Added pagination to the reports

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/filldb.py, gnowsys-ndf/gnowsys_ndf/ndf/views/event.py
* Bug resolved in ```filldb.py```  --> member_of is set for "CollegeEvent"
* Bug resolved in ```event.py```  --> minor changes.
=> Minor bug resolved 

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/create_schema.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/filldb.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/sync_existing_documents.py, gnowsys-ndf/gnowsys_ndf/ndf/models.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/trainer_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/course.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py, gnowsys-ndf/gnowsys_ndf/ndf/views/person.py, gnowsys-ndf/gnowsys_ndf/settings.py
**NOTE:** After taking this pull request, please perform following steps as specified:
1. Run following command: ```python manage.py filldb```
- This will create new META_TYPEs named as **Binary** and **Triadic**
- Error in filldb has also been resolved in this pull request
2. Run following command: ```python manage.py sync_existing_documents```
- This will set existing **RelationType** (RT) nodes' ```member_of``` field's value as **Binary** (META_TYPE)
- Because as of now all existing RT nodes represent Binary relation(s)
- Also updates ```object_type``` fields of two of the RTs. For more details refer below description (#3.2).
- Adds ```license``` field into existing Author node(s) only if it doesn't exists in their structure
3. **DONT FORGET** to update ```member_of``` field of any RT …
=> Binary & Triadic relation/relationship implementation and Voluntary teacher linking fix

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_nroer_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/landing_page_nroer.html, gnowsys-ndf/gnowsys_ndf/settings.py
- Added new slide in landing page.
- Updated variable in settings.py for NROER menu
=> NROER: Landing page and menu variable updated

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_nroer_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/landing_page_nroer.html
**NROER: Slide 2 text and appearence modified**
- Added stylish quotes in the 3rd slide.
=> Mongokit dev

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/filters.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
**Filters updated to show required features:**
- If no filters are added, filters area will not show up.
- As on when filters gets added, filters area will appears.
- Filters: `textcomplexity` and `educationalalignment` removed as per suggestion.
- Showing border prominent and not on hover.
- Showing filters count. Which gets updated dynamically.
- On hover of remove-filter button icon, showing strike-through on the text.
- On click of filters count, hiding select-filter widget.
=> Filters updated to show required features

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/event.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/scheduler_calender.html, gnowsys-ndf/gnowsys_ndf/ndf/views/event.py
Calendar is added to the event app you can see all the type of events for the specific month.
either on landing or on the click of view all calender appears
=> Calendar listing for event app done

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_thread.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/replytwistrep.html
* ```base.html``` modified
- Ajax-processing message will display on right-center corner of the screen. 
* ```create_thread.html``` modified
- Tool bar buttons/options of org-editor appearing twice fixed
- Thread creation fixed
* ```replytwistrep.html``` modified
- Continuous display of processing-message even after successful ajax-call completion fixed
=> Minor fixes

gnowsys-ndf/bower.json, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ebook.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file_list_tab.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/page_list.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/partner.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/partner_list.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/uDashboard.html
**Implemented epub reader for .epub files:**
- EPUB files are rendered into browser itself.
- `< Previous` and `Next >` are provided for navigating to pages.
- At bottom download button is given.
--
**Updated card's view**
- Much more things need to be changed. But for quick requirement satisfaction, updated CSS as phase - I update.
- In the next phase, we need to unify template for listing and apply the unique style for all. And next phase cards will be much more elegant than this.
- Being several templates used, currently it's not giving uniformity for the cards. Still I have covered most of them. There might be chances, few templates may left from change.
--
**To do:**
- After taking the this pull, do: `Bower install`
**TEST:**
- Upload sample .epub file. Go to detail view of that …
=> Implemented epub reader for .epub files and updated cards view

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/themes_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/drawer_widget.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/landing_page_nroer.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
* As per the requirement of NROER platform, we need to manage the workflow process as well as all type of users who handles the curation process.
*  All type of users will now be managed from group dashboard, (For NROER especially from home group)
* Types of Users are:
* Super Admin/ Super User
* Approver
* Curator
* Group Admin
* Partner Admin
* Registered User
* Guest User/ Anonymous
* Course Admin
* Event Admin
* Event Coordinator 
* "Home Dashboard" link is available now for NROER platform , in login user pull down menu, since with other platforms we have the provision to go to group dashboard. 
* New tab added in group dashborad page :  "Management"  , which is only visible to superusers and group admins of the group. Because only those users are responsible for management of users …
=> All Management Setting options for groups are available from Group Dashboard  

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_partner.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/uDashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/views/partner.py, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
1. user can create partner from dashboard itself by selection the drop down from <code>Become partner"</code>
2. <code>partner.html</code> modified as added some extra attributes in the create partner form
3.  after creating the patners all attributes gets store
4. notification send to the requested user who want to become a partner.
Now the basic flow is ready, <code>curation process</code> is in progress for time being disable the create partner button
=> modified workflow for creating a partner

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html
- Previously, ajax call for topic was made. Which was bringing the content, having unterminated string.
- So JS error was occurring and hence AJAX UI block "Processing Please Wait..." was appearing.
- Now this ajax call code is conditioned with `topic`.
- And locally tested for topic and page detail view. It's working fine.
=> Error while rendering node_ajax_view.html template is resolved

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_units.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_course_structure.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/login.html, gnowsys-ndf/gnowsys_ndf/ndf/views/course.py
When an anonymous user tries to perform any of the actions such as creating page, uploading file, etc which requires user authenticity, we show up the login form, after logging in , the user will now be redirected to the requested page.
The 'Login' butotn on the login form also the tabindex now.
added '@login_required' to the course view.
=> Redirect to requested page after login

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/discussion.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/__init__.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
**Discussion: Sending mail to creator of GSystem:**
- Now mails will be sent to creator of Page/File/.../GSystem on reply to discussion under it.
--
**Testing:**
- While testing run following:
`python -m smtpd -n -c DebuggingServer localhost:1025`
=> Discussion: Sending mail to creator of GSystem

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/collection_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_units.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_course_structure.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/course.py, gnowsys-ndf/gnowsys_ndf/ndf/views/course.py, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
-Hidden management tab in groups
-Show only draft or published status activities(i.e Pages, etc) in user dashboard
-Deleting courses from Course detail view
-On click on anywhere on template, if unit name is in edit mode, reset it
-Added login_reqd decorator to uDashboard so that an anonymous user cannot visit the dashboard of any user by link of username in card view or anywhere else.
-Redirect to course detail view from Course Authoring page (l.h.s)
-Expand the tree (collection_nav) in Course Detail
=> Minor changes

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/studentcourseenrollment_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/studentcourseenrollment_list.html, gnowsys-ndf/gnowsys_ndf/ndf/views/course.py, gnowsys-ndf/gnowsys_ndf/ndf/views/enrollment.py
Listing of Announced Courses in datatable
=> Editing StudentCourseEnrollment dates

INSTALL, requirements.txt
Added following dependencies for `sudo` level install in `INSTALL.txt` file:
- `memcached`
- `libevent-dev`
Added following packages for `pip` level install in `requirements.txt` file:
- `python-memcached`
- `django-memcache-admin`
- `pandora-client`
=> Updated requirements and INSTALL file according to recent changes

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/graph_collection.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/graph_concept.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/graph_dependency.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
**Tags adding functionality modified**
- While adding tags, it's been checked for not to accept special characters.
- Appropriate error message is flagged if 
- The tag-label gets created as on when tag gets added.
- Added tag can be removed by clicking on `X` on tag-label.
- If all the tags are removed, (previously) this change was not getting recorded which is now corrected.
- Tag-Label element's CSS modified for not to show capitalized letters.
- Added modified by information at bottom of detail view.
--
**Other changes**
- Showing `last modified` at bottom of detail view.
- Re-open graph for topics.
=> Tags adding functionality modified

gnowsys-ndf/gnowsys_ndf/ndf/views/course.py
Showing content in announced course
=> Showing content in announced course

gnowsys-ndf/gnowsys_ndf/ndf/views/course.py
Showing course details to anonymous user
=> Showing course details to anonymous user

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_detail.html
Removed redundant description from course details
=> Removed redundant description from course details

gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
bug fix regarding generic event is fixed.
=> bug resolved while creating generic events

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/mis_report.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/ajax-urls.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/mis.py
Implemented: Downloadable Reports for MIS
File changed: mis_report.html - Template with filters and data is shown using datatables.
Files changed: ajax_views.py - Added new view "get_detailed_report()" .
What to test: Under MIS_admin group, MIS GAPP, a link to Reports is provided.
Apply various filters and check whether data is getting populated properly. Also try to download the sheet.
=> MIS Reports

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/translation_page.html
minor changes made in content translation template.
1. textarea replaced with div.
2. label text bold.
=> content translation template modified

gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py, gnowsys-ndf/gnowsys_ndf/ndf/views/mis.py, gnowsys-ndf/gnowsys_ndf/ndf/views/page.py, gnowsys-ndf/gnowsys_ndf/ndf/views/person.py, gnowsys-ndf/gnowsys_ndf/ndf/views/quiz.py
VTs are displayed w.r.t new triadic relation 'trainer_teaches_course_in_college' instead of 'trainer_of_college'
=> MIS Voluntary Teachers in listing and reports

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html
1. Create New group will only be allowed to superuser (for time being)
=> Create New group will only be allowed to superuser

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/task_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/views/task.py
Task creator:
we can now create three type of task 
1) single task single assignee
2) Multiple task multiple assignees
3) Group task 
single task only a single task would be created for respective assignee
Multiple task :- each assignee gets a task by his name getting created,
the creator would also have the a task of his name under which all the created multiple
task will be visible
Group task:-   single task created with multiple attribute to it
=> Group task

gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
- `Altnames` for underlying moderated group's bug is fixed.
- Now with create/edit of moderated group's `moderation_level` `altnames` will be according to top-group.
- Bug reported in the previous commit is fixed.
=> Altname for moderated group's bug fixed

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/Captcha.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/login.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/__init__.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/captcha.py, gnowsys-ndf/gnowsys_ndf/ndf/views/Captcha.py, gnowsys-ndf/gnowsys_ndf/settings.py, requirements.txt
1) Created a separate template captcha.html.
2)  just have to include this html using {' % include 'ndf/captcha.html'  %'}
inside any form element.
3) can be used at different places  by using include tag , it wont allow any submit action to happen of the form in which it is included until we provide correct captcha
4) using mathematical equation for captcha example:- 4*3 = 12
=> captcha implemeted

gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
used a temporary variable at three places for faster appends on lists
=> implemented a optimizing technique in build_collection method

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/hierarchy_tree.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme_drag_zoom_d3tree.html
- SVG is made proper so that it can viewed in any viewer.
- showing teaches topics's in resources detail view's breadcrumb.
=> Minor issues like breadcrumb, SVG standard metadata in graph

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/person_details.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/student_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/student_list.html, gnowsys-ndf/gnowsys_ndf/ndf/views/person.py
1. On registering Student or Program Officer or Voluntary Teacher, earlier redirection was to list view, this has been changed to detail view now.
2. In student listing, on click on name of the student, earlier we redirected to create_edit form, this now changed to detail view.
3. New field added 'Aadhar Card number' (non-mandatory) for student registration.
4. Display proper data instead of node in person details template (for Student/PO/VT).
5. Display enrollment code if node is member_of Student 
6. Hidden the history/version part from details template.
Files required other that git files:
ATs.csv
property_order_reset.py
These will be forwarded on gnowsys mailing list.
=> MIS: Person detail & Student Reg

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/hierarchy_tree.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/moderation_data_review.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme_drag_zoom_d3tree.html
- Reduced top space to tree hierarchy
- Removed commented (shifted) code
- Moved top create `theme item` and `delete` buttons to LHS.
- Listing types of hierarchies on RHS of theme name.
- Highlighting currently selected theme name.
- making first child of the collapsible tree to open.
=> Tree layout changes

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/sync_existing_documents.py, gnowsys-ndf/gnowsys_ndf/ndf/models.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/uDashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/user_profile_form.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/user.py, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
Added a tab on user dashboard to take its information, with space would be used as place to fetch all sort of user related information.
modified models.py to added two extra field in Author class they are:
language_proficiency
subject_proficiency
write now user form only take first_name ,last_name language_proficiency and subject proficiency 
what to test
go to user dashboard click on info tab 
their we can see user related information           
click on edit to add info, to it
nothing is mandatory as of now
perform sycn_existing_documents for syncing the previous author nodes
=> Userinfopage

gnowsys-ndf/gnowsys_ndf/factory_type.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/filldb.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/sync_existing_documents.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/page.py
First - fire filldb to get the tree type of page instance i.e Info page,Blog page,Wiki page
now we have three type of pages Blog,page,wiki
what to test
default in drop down wiki should appear
if wiki is selected it should be editable by every one
if blog is selected should be editable by creator
if Infor page is selected should be editable by group admins
after above flow is tested perform sync_existing documents for converting all the pages to Wiki pages
=> pagetype info wiki blog implmented

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_nroer_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/themes/nroer/_theme_settings.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file_list_tab.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/image_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/landing_page_nroer.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html
- Only Front-end changes.
- Templates, SCSS, CSS files changed
=> NROER: landing page and theme updated. Subtle template issues solved.

gnowsys-ndf/gnowsys_ndf/ndf/views/notify.py, gnowsys-ndf/gnowsys_ndf/ndf/views/tasks.py, gnowsys-ndf/gnowsys_ndf/settings.py, requirements.txt
All notification mail task assigned through django celery
Test: check mail is going to respective user.
Required simultaneouly runs:
python manage.py celery worker --loglevel=info (for server, run in background)
For deploy on server following line required to added in .wsgi file
import djcelery
djcelery.setup_loader()
note: 
Require to installation pip install django-celery (already added in requirement.txt file)
=> Notification mail through celery task

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/nroer_data_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/views/file.py, gnowsys-ndf/gnowsys_ndf/settings.py
Implemented File upload controlling from settings
- variable `GSTUDIO_FILE_UPLOAD_FORM`
- possible values:
1. `simple`
2. `detail`
=> Implemented File upload controlling from settings

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/create_theme_topic_hierarchy.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/nroer_data_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/repository.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/registration_form.html, gnowsys-ndf/gnowsys_ndf/ndf/views/page.py
Commented part in page.py to get versions for every node while page listing
=> Commented part in page.py to get versions for every node while page listing

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/collection_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_units.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_course_structure.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_thread.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/forumdetails.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/thread_details.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/course.py, gnowsys-ndf/gnowsys_ndf/ndf/views/course.py, gnowsys-ndf/gnowsys_ndf/ndf/views/forum.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/page.py
Course Player is the dashboard of CourseEvent Group.
Implemenation:
A Course has Section, Subsection, Unit, Resources
A CourseEvent Group has SectionEvent, SubsectionEvent, Forum, Thread.
Course Player uses forums and threads.
It also has discussion course-wide
It also has Journal, adding blog pages.
What to test:
1.Create a Course.
2. Author it. Add resources with images,videos, pages with contents.
3. Announce it.
4. Go to CourseEVentGroup.
5. Forums i.e Units are listed in cards.
6. Click on any one of them. You will be able to see other forums of the group on LHS.
7.All the threads of respective forum will be displayed. If resource in course unit was image/video, it is added to content of thread.
8. Click on any thread, you will be able to see other threads of the forum on LHS.
9. …
=> Course player Part - 1

gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
Course Event Group will now hold CourseEventGroup GST _id.
Course Event Group will have moderation_level = -1
Redirection bug fixed on creation Course Event Group
=> Updates on Course Event Group

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/filters.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html, gnowsys-ndf/gnowsys_ndf/settings.py
- 'Curated zone' changed to 'Themes'
- Some other minor CSS changes
=> 'Curated zone' changed to 'Themes' and some other minor changes  

gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
Bug :- listing was not happening in college group for new registered users
status :- fixed
test:-
register new students and try them to list in student listing in mis.
=> students listing fixed

gnowsys-ndf/gnowsys_ndf/settings.py
**Captcha Updated**
- Previously, Captcha would generate Mathematical Expression,So  Result of Expression will be  correct captcha (the one user enters).
- Now Captcha will generate Characters only, so user must enter exact characters.
=> Captcha Updated

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/replytwistrep.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/twist_replies.html
**showing reply and delete buttons to thread reply**
=> showing reply and delete buttons to thread reply

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/UploadDoc.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_course_structure.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/replytwistrep.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/twist_replies.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/uploaded_files_for_replies.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/file.py, gnowsys-ndf/gnowsys_ndf/ndf/views/forum.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py, gnowsys-ndf/gnowsys_ndf/ndf/views/notify.py, gnowsys-ndf/gnowsys_ndf/ndf/views/task.py
**Corrected uploading of files from thread reply**
=> Corrected uploading of files from thread reply

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/res_node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/page.py
1. Hidden Edit CourseEvent button (since the functionality is not fully implemented)
2. Blog pages status as PUBLISHED (created from Note Book tab in Course Player)
3. Pages created/added in Event authoring will not be listed in Notebook tab
4. Announce button will be displayed ONLY to gstaff
=> Minor updates on CoursePlayer

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
**Showing blogpages to all course-group members**
=> Showing blogpages to all course-group members

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/Upload_File.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/Uploader_Form.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_selector.html, gnowsys-ndf/gnowsys_ndf/ndf/views/file.py
**Contributors form updated:**
- Added `Not Sure` option in `Subject` and `Level` fields of contributors form.
- Provided back-end support for the same.
- Metadata (LHS) updated.
**After file upload redirection changed**
- Previously, after uploading file, user gets redirected to list view.
- Now after uploading new or existing file, user will gets redirected to it's detail view.
-- 
**TEST:**
- To have contributor's detail form, overwrite following variable in `local_settings.py` file:
`GSTUDIO_FILE_UPLOAD_FORM = 'detail'`
- Try to select and upload new as well as existing file and check for it's redirection.
=> Contributors form updated. After file upload redirection changed.

gnowsys-ndf/gnowsys_ndf/ndf/views/custom_app_view.py, gnowsys-ndf/gnowsys_ndf/ndf/views/e-book.py, gnowsys-ndf/gnowsys_ndf/ndf/views/e-library.py, gnowsys-ndf/gnowsys_ndf/ndf/views/event.py, gnowsys-ndf/gnowsys_ndf/ndf/views/file.py, gnowsys-ndf/gnowsys_ndf/ndf/views/forum.py, gnowsys-ndf/gnowsys_ndf/ndf/views/imageDashboard.py, gnowsys-ndf/gnowsys_ndf/ndf/views/meeting.py, gnowsys-ndf/gnowsys_ndf/ndf/views/module.py, gnowsys-ndf/gnowsys_ndf/ndf/views/page.py, gnowsys-ndf/gnowsys_ndf/ndf/views/partner.py, gnowsys-ndf/gnowsys_ndf/ndf/views/quiz.py, gnowsys-ndf/gnowsys_ndf/ndf/views/search_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/task.py, gnowsys-ndf/gnowsys_ndf/ndf/views/term.py, gnowsys-ndf/gnowsys_ndf/ndf/views/topics.py, gnowsys-ndf/gnowsys_ndf/ndf/views/version.py, gnowsys-ndf/gnowsys_ndf/ndf/views/videoDashboard.py, gnowsys-ndf/gnowsys_ndf/ndf/views/wikidata.py
ins_objectid = ObjectId()
if ins_objectid.is_valid(group_id) is False :
group_ins = node_collection.find_one({'_type': "Group", "name": group_id})
auth = node_collection.one({'_type': 'Author', 'name': unicode(request.user.username) })
if group_ins:
group_id = str(group_ins._id)
else :
auth = node_collection.one({'_type': 'Author', 'name': unicode(request.user.username) })
if auth :
group_id = str(auth._id)
else :
pass
try:
group_id = ObjectId(group_id)
except:
group_name, group_id = get_group_name_id(group_id)
=> Replace with get_group_name_id wherever needed in the views

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/data_review.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/list_themes.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme_drag_zoom_d3tree.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_selector.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/topics.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/trash.py, gnowsys-ndf/gnowsys_ndf/ndf/views/data_review.py, gnowsys-ndf/gnowsys_ndf/ndf/views/topics.py, gnowsys-ndf/gnowsys_ndf/ndf/views/trash.py
**Enabled restore functionality from trash group:**
- `Restore` button in trash group enabled to restore respective resource in it's group/s.
- Try to delete page and theme instance and try to restore it from *Trash* group.
**Deleting theme functionality opened:**
- Enabled delete theme functionality.
- New template, url and method defined for listing and deleting theme.
- Try to list and delete listed themes.
- Updated selector widget.
- Try to add and remove apps.
=> Enabled restore functionality from trash group. Deleting theme functionality opened  

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/Captcha.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/uDashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/user_profile_form.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/login.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/registration_form.html
* /accounts/register
* /accounts/login
=> Templates  Redesigned for Mobile View

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/nroer_data_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file_list_tab.html, gnowsys-ndf/gnowsys_ndf/ndf/views/file.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
- Processing added new column - `thumbnail`
run : `python manage.py nroer_data_entry <file_name>`
=> Updated nroer_data_entry script

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_metastudio_settings.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/collection_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html
**UI changes: Search, Collection viewer and SCSS**
=> UI changes: Search, Collection viewer and SCSS

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/Upload_File.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file_list_tab.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/password_change_done.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/password_change_form.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/__init__.py, gnowsys-ndf/gnowsys_ndf/ndf/views/adminDashboard.py
**Created new template for change password:**
- Previously, we were using default django form/template to change password.
- Now new templates had been added under registration folder:
- `password_change_form.html`
- `password_change_done.html`
- Accordingly parameters are passed into the respective urls in `__init__.py` file.
--
- Updated `Upload_File.html` to have instructions and asterisk to show compulsory fields.
- Error while loading admin designer is resolved.
--
**NOTE:**
- Created new `CSS` class `.compulsory`, which shows asterisk at the end of that compulsory field name.
- Usage example: `<b class="compulsory">Language</b>`
=> Created new template for change password. And other minor changes.

gnowsys-ndf/gnowsys_ndf/ndf/templates/403.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/collection_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/program_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/password_change_form.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/course.py, gnowsys-ndf/gnowsys_ndf/ndf/views/file.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/program.py
Following points have been covered in this PR:
1. Added header to PE and CE to display info such as Event's name, start/end dates and enrollment dates.
2. This same header will hold the Enroll button.
3. If group is Private, and user is not member of it, redirect to Permission denied template(403-Forbidden Error)
4. CourseEvent and ProgramEvent group's _id is added to calling group's post_node field.
5. Button to list events from program player.
6. thread_create method is called after save_file method (in submitDoc)
7. Listing of PE & CE group-wide
=> Minor issues fixed

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/filters.html, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/tasks.py
**Video conversion logic is modified in tasks.py (django-celery)**
- Minor error in group.py solved
- filters text modified
=> Video conversion logic is modified in tasks.py (django-celery)

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/filters.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/e-library.py, gnowsys-ndf/gnowsys_ndf/ndf/views/file.py, requirements.txt
**Made collection tab as default and paginated**
- Previously, `All` means all the files was default. But now collections are made as default.
- Prior to this all the collection objects (cards) were getting land on first page load.
- Now this is made paginated.
- Back-end code in `file.py` and `e-library.py` updated to incorporate this flow.
--
**Other Changes:**  
- fixed versions of following packages in `requirements.txt`:
- `django-json-rpc`
- `pandora-client`
- Updated CSS of card a bit.
- Other minor fixes in templates.
=> Made collection tab as default and paginated and other changes

doc/schema_directory/ATs.csv, doc/schema_directory/RTs.csv, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/discussion.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/program_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/res_node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/search_page.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/under_moderation.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/course.py, gnowsys-ndf/gnowsys_ndf/ndf/views/file.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py, gnowsys-ndf/gnowsys_ndf/ndf/views/moderation.py, gnowsys-ndf/gnowsys_ndf/ndf/views/page.py, gnowsys-ndf/gnowsys_ndf/ndf/views/program.py
Note: RTs.csv and ATs.csv updated
1. New RelationType: 'has_logo'
2. In Course create/edit, now we can upload thumbnail. This thumbnail is displayed in the card listing of Course.
3. In Edit Course, if thumbnail already uploaded, a link is provided to see it. Otherwise, option to upload file is open.
4. For a Course a thumbnail can be modified. The 'Edit' option besides the existing thumbnail's link, reveals the upload file option.
5. If thumbnail is changed, the old thumbnail will be un-linked with current course, if same image is  used at other places, other wise the old img will be purged.
6. A Cancel button also provided.
7. Listing of Courses is now sorted based on last update
8. Changing status of Moderation Task (workflow) to CLOSED on final approval of resource to top level group …
=> Upload Logo feature provided for Course

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/footer.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html
1. Footer text changed from "Gnowsys-Studio" to  "gstudio"
2. In contributed by statement, "AT" word changed to "ON"
=> 1. 'Gnowsys-Studio' replaced by 'gstudio' 2.'AT' replaced by 'ON'

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/breadcrumb.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/user_profile_form.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/file.py, gnowsys-ndf/gnowsys_ndf/ndf/views/page.py, gnowsys-ndf/gnowsys_ndf/ndf/views/topics.py, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
**Minor changes:**
- Some of the card views in eLibrary was giving error is fixed.
- Changed text in filters.
- Hiding breadcrumbs for NROER (except in topic detail view)
- Getting back to tree hierarchy to explore till exact node issue is fixed.
- Removed eBook from eLibrary.
- Made hierarchical tree as default.
- Topic detail view: Showing resources according to language in fieldset.
- Showing edit in group profile only if logged in user is admin of dashboard.
- Made breadcrumb color to hyperlink color (blue).
- Modified listing of teaches resources in topic detail view.
- And some other minor errors fixed
=> Minor changes - fixed

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/uDashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/user_profile_form.html, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
Updates:
1. User profile photo upload bug fixed
2. Now user can either upload a new photo or choose from existing (old) profile photos
3. Updated user_profile info code.
4. Updated user dashboard layout
5. Course dashboard minor design bug(layout distorted in firefox) fixed
=> Updates in User-dashboard

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/nroer_data_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header.html
**Added BACK button functionality:**
- Added site-wide functionality of `BACK` button.
- Implemented at second level header
**creating "FILE NOT FOUND" from nroer_data_entry script:**
- This script is fetching resources from server.
- For *FILE NOT FOUND* error we needed to parse common log file.
- Now along with common log file, creating new `<file_name>_FILE_NOT_FOUND.log` file only if no resource/s found from provided CSV.
- This log file records: `name`, `url`, `file_name`
=> Added BACK button functionality and creating "FILE NOT FOUND" log file from nroer_data_entry script

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/search_page.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
* Applied new Card view for Search Results.
* Theme Graph (Themes template) is hidden if user accessing through Mobile Phone
=> Search page and Theme Templates Changed

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/uDashboard.html
uDashboard layout was resetted by # 1278. Layout updated again.
=> uDashboard updated

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/orgitdown/skins/gstudio/set.js, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html
* Previously in Orgit Down editor **cntrl + C** was shortcut for Cite, hence Copy command was not working.
now **cntrl + C** will be for Copy command
*  Meta Data Condition, which is creating problem while create and edit course is now removed.
Further  Discussion Needed to fix this issue.
=> Minor Bugs fixed

doc/schema_directory/RTs.csv, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/collection_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_units.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/uDashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/course.py, gnowsys-ndf/gnowsys_ndf/ndf/views/discussion.py, gnowsys-ndf/gnowsys_ndf/ndf/views/file.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
NOTE: RTs.csv updated
Course Event Updates:
1. Notebook:
Page listing will not contain course content related pages.
The username of author of page is now displayed.
2. Gallery:
Sorting based on last update
Upload File option
3. Commented notifications sending on commenting.
4. Units Authoring will now show collection-tree on LHS
5. Announcing Course bug fixed
=> Course player updates

doc/schema_directory/ATs.csv, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/collection_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/course.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/course.py
Note: Updated ATs.csv
1. Now, every subsection (i.e parent of unit), will have a date attribute.
2. Admin can only set the date from course player.
3. Users will be able to view only those subsections whose date is reached.
( current date greater/equal than/to release_date)
4. If no release_date is set, users will be able to view it.
5. Admins can see complete course structure irrespective of release_date.
6. Collection-tree (on LHS), will have a scroll-bar if extends default height( fyi 300px).
7. Removed keyboard up/down keys binding from collection-tree
Meanwhile, also test for regular collection-tree.
For this go to detail view of any collection from file-listing
=> Release dates feature in course player

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py, gnowsys-ndf/gnowsys_ndf/ndf/views/page.py
1. For every page/file on create/edit, interaction_settings will be mandatory.
2. This check has been excluded for blog page creation from Notebook of a course player.
3. But such blog page will still have a thread created(implicitly i.e w/o user's intervention & with default values (no start/end dates)).
=> Updates on Notebook (Course Player)

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/discussion.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/res_node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
1. Edit course-event-group
2. Rating removed from course content
3. Adding ordered list in Text editor (reply orgitdown)
4. Discussion button will display number of replies
=> Minor updates in course player

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/invite_admins.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/invite_users.html, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py, gnowsys-ndf/gnowsys_ndf/ndf/views/notify.py
1. Script added to search in a drawer for Subscribe Users/Admins
2. Populate users in subscribe admins drawer
What to test:
Search for a user from the search box of the drawer.
Also, the text to be searched is trimmed.
Try subscribing an admin and a user after/before search
=> Bug fix: Search feature in subscribing users/admins drawer

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/discussion.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/invite_admins.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/invite_users.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/program_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/res_node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/under_moderation.html, gnowsys-ndf/gnowsys_ndf/ndf/views/discussion.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
1. Dates header in eCourses/events is removed; instead this info is displayed in about tab.
2. Uploading file in event from discussion will send resource to moderation, also content of reply will intimate the user providing a link to check status of resource
=> Minor updates

gnowsys-ndf/gnowsys_ndf/ndf/templatetags/simple_filters.py, gnowsys-ndf/gnowsys_ndf/ndf/views/e-book.py
- Showing only collection instances on eBook filters
- Getting git hash code updated in `simple_filters.py`.
=> Showing only collection instances on eBook filters and getting git hash code updated

gnowsys-ndf/gnowsys_ndf/ndf/views/analytics.py
On click of Group analytic in the CourseEvent Group their was error .
resolved it.
=> fixed group analytics error

doc/Migrating_SQLite_DB_to_PostgreSQL.txt
Documentation for transfering data from `SQLite` to `PostgreSQL`:
- Includes detailed steps to install `PostgreSQL` and creating user and database.
- Includes detailed steps to take dump from `SQLite` to `PostgreSQL`.
=> Documentation for transfering data from SQLite to PostgreSQL added

gnowsys-ndf/bower.json, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header.html
**Added new 585 fonts with font-awesome bower dependency**
- Now along with foundation icons new set of icons had been added.
- Included in `base.html` file.
- `Font-Awesome` comes with bower dependency.
- Use it with `<span>` or `<i>` tag.
- It can be used with variations like *spinning-moment*, *angle-rotated*, *fixed-width* and with many other conditions/variations.
--
**Example:**
`<i class="fa fa-angle-left"></i>`
--
**Useful Links:**
[All Icons](https://fortawesome.github.io/Font-Awesome/icons/)
[How to use](http://fortawesome.github.io/Font-Awesome/examples/)
[cheatsheet](https://fortawesome.github.io/Font-Awesome/cheatsheet/)
=> Added new 585 fonts with font-awesome bower dependency

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_details_base.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/ajax-urls.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
Showing breadcrumb for files, while coming from topics
=> Showing breadcrumb for file detail view, while coming from topics

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/nroer_data_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/views/topics.py
Showing breadcrumbs for theme to elements
=> Showing breadcrumbs for theme to elements

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/action_panel.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_partner.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/simple_card.html, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/partner.py
1. New button in action-panel if in one of Partner groups
2. New field added for altnames in partner creation form
3. Sort subgroups last update wise in group dashboard
4. Sort sub-partner groups last update wise in partner listing
5. Changed date format in card to 'dd-mm-yyyy'
=> Minor updates on Partners and others

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/action_panel.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/event_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/groupdashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_details_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/res_node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/course.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/page.py, gnowsys-ndf/gnowsys_ndf/ndf/views/program.py
Removed buttons: History, Analytics, Translate
Test with three logins:
- SuperUser/ Admin User
- Regular User
- Anonymous User
Test views:
- Group dashboard
- Resource detail view
- Topic detail view
- also check other possible view.
Buttons have tool-tips now, if disabled.
=> Action panel redesigned

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/create_theme_topic_hierarchy.py
Updated create_theme_topic script to incorporate language field"
=> Updated create_theme_topic script to incorporate language field

gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/login.html, gnowsys-ndf/gnowsys_ndf/ndf/views/partner.py
Opened registration link for NROER
=> Opened registration link for NROER

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/simple_card.html, gnowsys-ndf/gnowsys_ndf/ndf/views/file.py
Displaying static img if prof_pic/has_logo not found for Groups/Partners, in card listing
=> Update in card listing

gnowsys-ndf/conf/locale/hi/LC_MESSAGES/django.po, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/action_panel.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/group_dashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/hierarchy_tree.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/invite_admins.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/invite_users.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/page_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/repository.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/task_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/uDashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/upload_pic_widget.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/login.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/password_change_form.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/password_reset_error_form.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/password_reset_form.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/registration_closed.html
Trans tags added
English messages changed
=> Changes related to Hindi Translation

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/main_simple_card.html
* now cards can have .svg as thumbnail in main_simple_card.html.
=> svg thumbnail Error

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/partner.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/partner_list.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/simple_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/program.py
1. Displaying status of Event based on Start/End Event and Enrollment dates.
2. Upload logo feature added in Program/Course Event create/edit form.
3. Displaying mid-size image in the card view of PE/CE
4. Sorted listing of PE
=> Event status in Card (Open/Closed/Forthcoming) and other minor updates

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/collection_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/footer.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/landing_page_nroer.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_details_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/repository.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html
* On Image Hover, Icon is provided to view image in Full Screen.
* Particular Theme's Title and Description is provided on top
* 100% with for Banner images
=> CSS Changes

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/footer.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/login.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/e-library.py, gnowsys-ndf/gnowsys_ndf/settings.py
- Footer issues to redirect to issues page.
- Filtering pages in e-library.
- Adding e-mail for registration.
=> Footer issues to redirect to issues page. Filtering pages in e-library. Adding e-mail for registration.

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/action_panel.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/collection_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/discussion.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ebook.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/footer.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/settings.py
Following bugs/changes fixed:
* link is provided for How to read ePubs in eBooks listing.
* Configurable social n/w share button now.
* List Members button only visible for gstaff users.
* text getting out of comment box issue fixed now.
=> Bugs Fixed

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/create_theme_topic_hierarchy.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/filldb.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/nroer_data_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/views/file.py
**Filldb to create 'warehouse' group:**
- New group - `warehouse` will gets created.
--
**Updated nroer_data_entry script**
- Fixed following issues:
- Spaces in url handled.
- Not adding same `_id` in `collection_set`.
- Adding thumbnails in `warehouse` group.
=> Filldb to create 'warehouse' group. Updated nroer_data_entry script.

gnowsys-ndf/gnowsys_ndf/ndf/views/e-library.py, gnowsys-ndf/gnowsys_ndf/ndf/views/moderation.py, gnowsys-ndf/gnowsys_ndf/ndf/views/task.py
- Filtering eBooks from eLibrary.
- Updated domain-url correctly in notification mail text.
-- 
**TEST:**
- Get into eLibrary and check for not getting eBook/ePub instances in the listing.
- Try to put filters and check the result.
- Click on different categories on LHS and check the result.
- Start smtp server and try to upload file in moderated group and check the mail text. Expect url and not domain name in the clickable link of mail body.
=> Filtering eBooks from eLibrary. Updated domain-url correctly in notification mail text.

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/action_panel.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html
* action panel - on hover of button,title was getting crop problem fixed now.
* Themes title  will not appear in detail view of topic now.
=> UI changes and minor bugs fixed

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gcollection_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gcourse_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gheader.html, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
I have made changes in collection view. Also added number of children elements on right side of each section, sub section and unit.
Check it out and provide me feedback.
=> Khaal - collection view in left sidebar

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_summary.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gcourse.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/side_group_panel.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
- scaffold for course summary created.
- added ndf_tag to get user concern course event groups.
=> khaal: scaffold for course summary created

gnowsys-ndf/gnowsys_ndf/factory_type.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/filldb.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/nroer_data_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/simple_card.html
**Updated nroer data entry script to create relation for thumbnail with resource:**
- Previously if thumbnail field does exists, we used to store uploaded thumbnail's `_id` in `fs_file_ids` of that resource.
- Now we are creating relation: `has_thumbnail` for attaching thumbnail with resource (if thumbnail does exists).
- Same relation is being used for showing thumbnail in card listing. And if relation does not exists, we are showing thumbnail generated from uploaded image.
--
**Other Changes:**
- Now we can specify type of relation in `factory_type.py` (e.g: `Binary`, `Triadic`)
- Updated `filldb` to accommodate those changes.
- Added new relation type `has_thumbnail` in `factory_type.py` file.
=> Updated nroer data entry script to create relation for thumbnail with resource

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/Upload_File.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/discussion.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gcollection_ajax_view.html
This includes nested accordion implementation which enables sub sections to be collapsible. Also at a time only one element of accordion can be expanded.
=> Khaal - Accordion Based Collection VIew

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/task_details.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/uDashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/moderation.py, gnowsys-ndf/gnowsys_ndf/ndf/views/task.py
* Subgroups not visible in details view of partner's group issue fixed.
* Edit and Update buttons will not be visible if task_type = "Moderation"
* Error in rendering Versions (task_details)fixed
* Logo for home group is configurable and will be appear on second level header
=> Issues fixed regarding : Task,dashboard and some css

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
* Even in wiki page now ckeditor will be used.
* Typeof of Page [Wiki, Info, Blog] can be edited now.
What to test:
1. Create and edit page from Page Gapp
2. Create and edit page from Course Units 
3. Create and edit page from from Notebook app of Course player
4. Try creating any node where ckeditor is used to enter content
=> Replaced org-editor with ckeditor

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/action_panel.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/analytics_views.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/collection_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/res_node_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/ajax-urls.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
To Count Visits from Benchmark:
* Removed visits code from action_panel and created new template for analytics visits - analytics_views.html
* Replaced label 'views' with 'visits'
* Renamed ajax-view 'get_views_count' to 'get_visits_count'
* Changed request method for collection-navigation ajax-view 'collection_nav' from 'POST' to 'GET' as the method is used to fetch data.
Modification in Writing to Becnhmark:
* Using the GET parameter during collection_nav, modify the benchmark instance's field 'calling_url'.
=> Using benchmark to get resource's visits count (in context of course player also)

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_units.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/quiz_item_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/quiz_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/course.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/quiz.py
1. Replace org-editor with ck-editor in quiz-item create/edit view
2. In course-units, from resource listing, redirect Quizitem/Quizitemevent to its edit view
3. Quiz-player loading bug fixed
4. Edit CourseEvent bug fixed (ndf_tag : get_relation_value)
5. Help text added to select multiple correct answer in Quizitem create/edit
Quiz-player:
1. Submit answer iff selected answer is not an already answered. (Preventing ajax call)
2. On click of radio-button in case of Single-Choice, hide check and cross icons
3. Load Short-Response user answer (if already answered) in text-area
=> Updates in Quiz module

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/event_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/simple_card.html
Course-Player:
* Displaying blog pages as cards
Cards:
* Do not display check-box in cards if 'no_checkbox' flag is passed as True while including simple_card.html
=> Blog pages listing in Course Player

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/event_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/quiz_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/quiz.py
**Quiz Player:**
* Show number of times a user attempted the quizitem
* Do not show 'Submit' button, if 'Show Correct Answer' flag is set True for a QuizItem
* If user has already submitted an answer, disable 'Submit' button till user makes changes to his/her answer.
* Added comments for all JS functions of quiz_player.html
**Course Player:**
* Changed label
- 'Journal' to 'NoteBook'
- 'Add Blog' to 'Add Note'
* Sort blog pages based on creation datetime (recent first)
=> Minor modifications in Quiz & Course Player

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ImageDashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/simple_card.html
* svg and gif  thumbnails were not rendering on card issue fixed.
* thumbnail  not rendering as per resource type issue fixed
=> thumbnail not rendering on card 

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ImageDashboard.html
* Upload images from local machine functionality added in ck editor's 'addImage plugin'.
=> Upload image from local system

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_selector.html
**Selector widget: Modified JS and html to have classes instead of ID's:**
- So that it can be used at many places in same template.
=> Selector widget: Modified JS and html to have classes instead of ID's

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/explore.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_selector.html, gnowsys-ndf/gnowsys_ndf/ndf/views/explore.py
1. Under explore- base course listing, option provided to 'Create New Course'
2. Listing of Course, Groups and Base Course according to date
3. If a non-gstaff user hits the basecourse url, it will be redirected to explore courses.
=> Create Course option.

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/groupdashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/in-line-texteditor.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/simple_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/login.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/ajax-urls.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/settings.py
* in line comments without refresh added in mongokit
* altname preference in simple card
* added css for in line comments
=> Comments without refresh(mongokit)

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/nroer_data_entry.py
**Updated nroer_data_entry script to create separate log file for unprocessed/erroneous rows/files:**
- We are logging all the information in the `<file_name>.log` file while processing the spreadsheet.
- But it was logging all the minute steps during processing. And it's difficult to understand, rows which haven't processed completely.
- Now, new file named: `<file_name>_ERROR_ROWS.log` will gets created.
- This file will hold:
1. Row no.
2. File name.
3. Error.
4. Complete row's data as a json dict (to record data at that point of time).
=> Updated nroer_data_entry script to create separate log file for unprocessed/erroneous rows/files

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gin-line-texteditor.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/html_editor.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/__init__.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/discussion.py, gnowsys-ndf/gnowsys_ndf/ndf/views/discussion.py
* Edit Button on each comment.
* Necessary URL's and Views added in discussion.py
=> In line edit option for thread(comments)

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gin-line-texteditor.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gnotebook.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/note_page.html
* Showing full name on notebook,discussion and notes page.
=> Full name at notebook and several plcaes.

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/filldb.py, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss
Creating 'help' as a new group from filldb, if does not exists.
=> Creating 'help' as a new group from filldb, if does not exists.

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gcollection_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
What to test:
* Complete a module ('Complete' means commenting on every resource that is inside a module), and check the progress-bar (Green colour) in course player
Updates:
1. Using ajax call instead of getjson call to build course content tree.
2. Display course progress bar (only if user is authenticated) based on the data values passed from views.
3. Removed course highlighting status related code from ajax-view get_collection.
4. Updated course-player tab views to pass progress bar related data and course-enrollment-allow-status flag to template.
5. Defined two new methods:
- get_course_completion_status: calculates the completed percentage of course w.r.t logged-in user and returns data-dict holding completion %, counts of completed and total modules; or if ids_list flag is passed …
=> Progress bar in Course player

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/analytics_views.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ggallerymodal.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ggallerypage.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
What to test:
1. In course-player, click on any of the Gallery/Raw-Material listed resources, the overlay opens with the selected file's detail view. Check the url. 
2. Close the overlay, check the url again. 
3. Apply filters, click on filtered results, and do follow above steps [1 & 2]  again.
4. Visits count from Analytics: Click on 'Click here to see no of visits'.
This is present in:
- Notebook note-page,
-  file detail overlay of Gallery/Raw-Material, 
- action-panel(RHS of any file-detail view)
Click on it, the earlier text is changed with 'Loading' till the results are fetched.
=> Unique URL for Gallery & Raw-Material file detail.

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/data_review.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/data_review_tbody.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/moderation_data_review.html, gnowsys-ndf/gnowsys_ndf/ndf/views/trash.py
1. Alert message for user's confirmation to Purge and Restore Actions
2. Purge and Restore views updated to pass response_dict basis on which message is displayed on template
What to test:
- Go to 'Trash' group.
- Try to Purge and/or Restore and resource.
- Check for an alert message. Confirm and continue and/or Cancel and abort the action.
=> Updates in Trash data-review

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html, gnowsys-ndf/gnowsys_ndf/ndf/views/file.py, gnowsys-ndf/gnowsys_ndf/ndf/views/imageDashboard.py, gnowsys-ndf/gnowsys_ndf/ndf/views/videoDashboard.py
Updates:
1. Spell error fix in node_edit_base class 'help_info_page'
2. Import get_relation_value from ndf_tag in file.ppy, videodashboard.py, imagedashboard.py
3.  Pass appropriate node variable in above 3 files while creating GRelation has_help
=> 'has_help' module bug fixes

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py, gnowsys-ndf/gnowsys_ndf/settings.py
Bug :
- Once we are enabling Interaction settings, no comment button is displayed and action panel comes below.
- And go back and check the Interaction settings and it is showing no.
Fixed the above bug.
=> Bug fixes in applying Interaction Settings

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gin-line-texteditor.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gnotebook.html
* New UI changes in notebook are reverted.
* new code is commented.
* audio js path added in gin-line-texteditor
=> Notebook UI changes reverted

gnowsys-ndf/gnowsys_ndf/factory_type.py, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/js/ckeditor-config.js, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/UploadDoc.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/Upload_File.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_create_collection.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_create_note.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/edit_thread.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/forumdetails.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gallery_raw_create_note.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ggallerypage.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gin-line-texteditor.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gnotebook.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/group_dashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/groupdashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/simple_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/thread_details.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/uDashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/upload_pic_widget.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/ajax-urls.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/e-library.py, gnowsys-ndf/gnowsys_ndf/ndf/views/file.py, gnowsys-ndf/gnowsys_ndf/ndf/views/forum.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
* Create note ,create collection and add to existing collection enabled in raw material and gallery tabs.
* Collection can be made up of minimum 2 files such as image,pdf,video,page etc.
* User can add number of existing images while creating a note(support for other mime type is not included in this commit).
* Pagination is added in raw material and gallery
=> Create note and collection in raw material and gallery

gnowsys-ndf/gnowsys_ndf/ndf/views/filehive.py, gnowsys-ndf/gnowsys_ndf/ndf/views/tasks.py
**Filehive: Video conversion via celery queue**
- Updated `views.tasks.convertVideo()` to incorporate filehive changes.
=> Filehive: Video conversion via celery queue

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ImageDashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/UploadDoc.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/action_panel.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/audioDashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_create_note.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ggallerymodal.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ggallerypage.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/simple_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/ajax-urls.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/imageDashboard.py
* write_file method added in uploaddoc(tested and working fine).
* get_file_size ndf tag to fetch file size as per file hive class.
* modified raw material and gallery cursor  to fetch file hive fields.
=> File read and write methods implementing throughout gstudio

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/quiz_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/unit_player.html, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py, gnowsys-ndf/gnowsys_ndf/ndf/views/quiz.py
Updates:
1. Show Submit button by default to all quizitemevents & display already submitted answer.
2. Modification in method get_course_completetion_status, to include QuizItemEvent along with Page, File leaf nodes
3. Do not show Comment option in unit player if node is QuizItemEvent member
4. As name of quizitem is coming from its html content, strip/remove html tags before assigning it to name
5. Posting answer on quizitemevent, update thread node's author set
=> Quiz-player updates

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_analytics.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
Course analytics will now be called on click on button
Admin will see all students analytics in tabular format
* Other UI updates from Ritesh
=> Group-admin analytics and UI updates

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ggallerymodal.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/views/imageDashboard.py
* Only those images will be appear which are uploaded by particular user in imageDashboard.
* images will be sort on the basis of last updated
=> Query changed in image dashboard

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gcollection_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gin-line-texteditor.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/discussion.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/discussion.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
When a new comment is added by any user, an alert msg is displayed showing the count of new comments and request the user to refresh to see the new comments.
=> Update comments section. (Loading new comments)

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/filldb.py
**Commit Highlights:**
* filldb (Bug-fix): Missing variable reference (node_doc) on new object creation issue fixed.
=> filldb (Bug-fix)

doc/deployer/create_authusers_from_code_username_password_csv.py, gnowsys-ndf/gnowsys_ndf/factory_type.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/filldb.py, gnowsys-ndf/gnowsys_ndf/ndf/models.py
**Script for creating users and authors:**
- This script will take input of CSV (having three columns school-code, username, password).
- script put in `/doc/deployer/` folder, named: `create_authusers_from_code_username_password_csv.py`
- Creates django user as well as mongo author object at once.
- Log file generated:
- `.log` which contains detailed textual info.
- `.csv` which contains: `school-code | username | password | operation-status(success/error-exception) | django-user-id | mongo-author-objectid`
- Additional changes:
- Added `create_author` method in `Author` class.
=> Added script for creating users and authors

gnowsys-ndf/gnowsys_ndf/ndf/views/page.py
* Error while create or update page from Page app and Course Content fixed.
* Check if you get custom error page while edit page
=> Bug in page creation and editing

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ImageDashboard.html
* SVG image was not showing properly in add image page of ckeditor.
* Now SVG's are rendering and also while adding  existing SVG image,it is getting uploaded.
*  Cursor : pointer is added to image and caption
=> Svg image not rendering in add image page(editor)

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/js/ckPlugins/addImage/plugin.js, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ImageDashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gcourse_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ggallerypage.html, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/imageDashboard.py
* File upload view changed in editor, gallery and editor.
* Image preview option provided in add image page of editor.
* Pagination area sifted in gallery and raw material as per latest design changes.
* Raw material file upload query changed, files which are uploaded in raw material will be saved as special  tag  "raw@material". hence the files which have this tag will be shown in raw material (excluding files uploaded from other places)
=> File upload view  in editor and gallery,raw material

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ImageDashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/simple_card.html
* Card view was breaking because description had html content.
=> Html description not showing on card error 

gnowsys-ndf/gnowsys_ndf/ndf/models.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
**File delete issue fixed:**
- Modified function in `models.Filehive` class.
- Added more check and validation in `delete_file_from_filehive()`.
--
**Test**
- try to delete/purge file from data-review of group.
=> File delete issue fixed

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/users_mgmt.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/ajax-urls.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/analytics_methods.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
Settings menu of Course-player will have new option: **Manage Users**.
This will take you to new template where based on name(search), users are fetched and listed along with a **Change Password** option.
In future, new option such as *Set Agency Type* can be added to the same template
=> Analytics optimization & Course-player: Manage users option. (Change Password)

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/action_panel.html
1. Wiki page can be edited by any group-member.
2. Subscribe user/admins from action panel bug fixed
=> Wiki page logic added

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/upload_pic_widget.html, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
1. Removed redundant code for fetching current and old banner pics of course player and moved it into one function `_get_current_and_old_display_pics`.
2. Replaced 'inline styles' with 'internal styles' of `upload_pic_widget.html`
=> Removed redundant code from course-player tab views

gnowsys-ndf/gnowsys_ndf/ndf/models.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/discussion.py, gnowsys-ndf/gnowsys_ndf/ndf/views/analytics_methods.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/imageDashboard.py
**Optimized Group Analytics:**
- Redefined `gcourse.course_analytics_admin()`.
**Time issue in models fixed:**
- At some of the places, we used `datetime.datetime.utcnow()`
- Which is now replaced with `datetime.datetime.now()`
**Get mid size image function modified:**
- Incorporated logic of file hive in `get_mid_size_image()`.
=> Optimized Group Analytics and other changes

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/explore.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/upload_pic_widget.html, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py, gnowsys-ndf/gnowsys_ndf/ndf/views/quiz.py
New implementations:
1. Forking of Nodes data:
- Update new node's origin field with {'fork_of': old_node._id} 
- Removed 'clone_of' RT
2. Forking of Triples data:
- GAttributes
- GRelations: Fork the right subject node also.
Hence, when we announce a course now, the announced course will have all data independent of any other group.
=> Forking of Course on Announcing.

gnowsys-ndf/gnowsys_ndf/ndf/models.py, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
While announcing, modified triples documents insertion strategy from _insert_ command to calling _create_grelation/create_gattribute_ methods
=> Forking triples logic changed

doc/deployer/delete_courseevent.py, gnowsys-ndf/gnowsys_ndf/ndf/models.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py, gnowsys-ndf/gnowsys_ndf/ndf/views/quiz.py
Commits added:
1. Handle unknown fields and missed fields error while saving
2. Unit -authoring: Replicate resource if the resource is out of group
3. Comment 'Set release dates' option from course settings dropdown
4. While replicating the resource, clear the prior & post node fields also
What to test:
Announce a course C1 to C2. Delete C1 and check whether C2 is running smoothly.
Have some quizitems also in C1. Try to attempt them in C2 after announcing.
=> Bugs found in Announcing fixed and other changes

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_metastudio_settings.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/landing_page_nroer.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/login_clix.html
Made homepage and login page of CLIx responsive.
=> Responsive

doc/deployer/delete_courseevent.py, doc/property_order_info.org, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_about.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/user_course_analytics.html, gnowsys-ndf/gnowsys_ndf/ndf/views/analytics_methods.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
1. Displaying of pie chart enabled in user/individual analytics.
2. Unit authoring bug in save_resources function fixed
3. Documentation of property_order 
4. Pass altnames in Property-order field considering type_of field.
5. Completed and total units count bug fixed
=> Displaying pie-chart for user/individual analytics

gnowsys-ndf/gnowsys_ndf/ndf/models.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gapps_iconbar.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/page_list.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/settings.py
**Buddy analytics methods added:**
- `get_all_buddies_auth_ids()`
- Returns all buddies `Author` _id's list
- `get_all_buddies_user_ids()`
- Returns all buddies `User` _id's list
- `get_buddy_userids_list_within_datetime()`
- Returns list of buddies user _id's at provided `datetime.datetime` object and loggedin_user's id.
--
**Implemented authorization for creating resource in concern group:**
- Allowing create resource only for authorized users
- Added `user_access_policy` in base.html so it's available all other child templates. Reduced re-calling same ndf_tag again at multiple places.
- Passed global `user_access` variable to get_gapps_iconbar ndf_tag.
- Modified `get_gapps_iconbar()` to take and pass user_access variable.
--
**To Test**
- Try to access same group url with different …
=> Buddy analytics methods added. Implemented authorization for creating resource.

gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
=> Creating GRelations with multiple Help pages while announcing bug fixed

gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
**master branch**
Note: Take pull from mongokit, as PR #1524 is expected to be on master branch also.
What to test:
Go to any edit of node(node_edit_base.html), page, file, group(depends on #1524 ), and click on tabs like   _Collection_ that fetches drawers.
You may also check the drawers functionality, from unit authoring page, before adding any dynamically created resources to a unit, try to add from existing resources(this calls drawer_widget) in a blank unit (unit without any resources in it yet)
=> Drawer widget bug fixed

gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
- Previously when new course is announced, newly announced course used to have content same as parent course group (instead of adding new/different content in course announce form).
- This is fixed. Now content added in announce course form will be considered.
- If content is not provided, parent group's content will be placed.
--
**TEST:**
- Announce new course and add custom content. Check for newly added content got reflected in announced course or not.
=> New course group announce time bug of overwriting content by parent group is fixed

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_details_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/page_list.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/page.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/page.py
* Show collection button was misplaced hence it is shifted to left side panel.
* Added pagination in Page App.
* Moderation condition added while uploading files in filehive.
=> Pagination in Page app and moderation bug fixed.

gnowsys-ndf/bower.json, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/main_simple_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_details_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/simple_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/upload_pic_widget.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/video_thumbnail.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/ajax-urls.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py, gnowsys-ndf/gnowsys_ndf/ndf/views/videoDashboard.py
* User can take snapshot from HTML video player and save it as thumbnail for particular video.
* All thumbnail will store in Warehouse group.
* Added `blueimp-canvas-to-blob` javascript  to convert canvas element to Blob object.
* Please run `bower install blueimp-canvas-to-blob`   use `--allow-root` option if running docker
=> Thumbnails for videos customizable.

gnowsys-ndf/bower.json, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/main_simple_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_details_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/simple_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/upload_pic_widget.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/video_thumbnail.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/ajax-urls.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py, gnowsys-ndf/gnowsys_ndf/ndf/views/videoDashboard.py
* Broken image was appearing if collection error fixed.
* Change thumbnail for file,page etc button css changed.
* Note: run `bower install --allow-root`
=> show collection image error

doc/deployer/copy_move_group_files.py
**Updated move_copy_group_files script:**
- Previously this cript used to move/copy only *File's*
- Provided option to copy/move page's too.
=> Updated move_copy_group_files script

gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
* Check file upload through detail form view .
* While uploading from raw material,check if raw@material tag is added by default
=> raw material tag bug 

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/quiz_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/simple_filters.py, gnowsys-ndf/gnowsys_ndf/ndf/views/quiz.py
1. Incrementing quiz-correct-ans Counter class field for User. 
2. Pre-select already submitted answer in quiz_player
=> Bug fixes in Quiz module

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/filters.html, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
Following are the updates:
1. Fetch results as per applied filters
2. Show image on card of filtered results
3. If filters removed, show original tab view (gallery/raw-material)
4. Include superusers of site as admins. show their uploaded files in raw material.
5. On clearing all filters, clicking on add filter, preselects first value 'Select'
=> Updates on filters in course player

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/nroer_data_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/simple_card.html, gnowsys-ndf/gnowsys_ndf/settings.py
* Script modified to add description and tags.
* Please test with proper csv
=> nroer_data_entry script bug

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_partner.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/edit_forum.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/main_simple_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html, gnowsys-ndf/gnowsys_ndf/ndf/views/forum.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
* Explore button hidden for NROER.
* Updates button will be only appear to admin if NROER.
* Repository,Partners and Groups all time visible.
=> NROER Issues

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ebook.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html
* Left hand panel look changed in themes and ebooks
=> NROER minor css issues fixed

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/under_moderation.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/login.html, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
* User name text changed on login screen.
* On eBook page showing count.
* On file detail view instead of showing contributed by for nroer it will be source of file.
=> Showing count on eBooks page

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/nroer_data_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/collection_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_course_structure.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/upload_pic_widget.html, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
* Bug in nroer_data_entry to upload ePubs fixed.
* Processing screen added in opening collection.
* Error in user dashboard when users relation set is empty fixed.
=> ePub CSV bug and Processing screen added.

gnowsys-ndf/fabfile.py, requirements.txt
**Initialized use of Fabric in gstudio project**
- Implemented python [Fabric](Fabric is a Python (2.5-2.7) library and command-line tool for streamlining the use of SSH for application deployment or systems administration tasks.) which is a command-line tool with the ability to execute commands on a local and remote server. It is designed (to use SSH) to execute system administration and deployment tasks on one or more remote machines.
- It has N no.of possibilities that we could make use of.
- As no of administrative scripts gone increasing, it is needed to make things easy and life of sysadmin happy :)
- Currently as sample/demo I have implemented following `fab` commands:
- `fab copy_schema_csvs`
- Copies schema files into `schema_files` folder.
- `fab update_data`
- Copies all the …
=> Initial implementation of Python Fabric

gnowsys-ndf/gnowsys_ndf/ndf/models.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_details_base.html
* Teaches relation gives error fixed.
* Error while accessing relation type fixed.
=> Bugs fixes after  changing triples schema

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/scrolldata.html
* Overlapping issue of  notification text on group update page fixed.
=> Notifications text css updated

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/export_users_analytics.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
**Added command to export (course) users analytics in CSV format:**
- Command will export all the user's analytics data, under group's to CSV format.
- File will created with following format:
- `schoolcode-course-name-datetimestamp.csv`
- `schoolcode` is `GSTUDIO_INSTITUTE_ID`
- This file will gets created under folder named: `gstudio-exported-users-analytics-csvs` under `/data/` folder.
- Updated `gcourse.course_analytics()` accordingly.
---
**TEST:**
`python manage.py export_users_analytics`
- It will ask for to enter either group name or id.
- File will gets generated under: `/data/gstudio-exported-users-analytics-csvs/` folder.
=> Added command to export (course) users analytics in CSV format.

gnowsys-ndf/gnowsys_ndf/factory_type.py, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/basecourse_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_about.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_course_structure.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/event_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/explore.html, gnowsys-ndf/gnowsys_ndf/ndf/views/explore.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
For any course that will be created henceforth, will be an instance of  **Group** and a member of new GST **BaseCourseGroup**.
What to test:
1. After taking pull, run following commands:
- `python manage.py filldb`
- This will create new GST BaseCourseGroup
- `python manage.py create_schema ATs.csv`
- This will reset start_time and end_time ATs
2. Click on `Explore` from header. Check BaseCourses listing (you should log in with admin account to view the base courses)
3. Create new course. After saving, it should redirect to course-player UI, with only 3 tabs, About, Content and Raw Material.
4. Try doing some editings to the same course and saving it.
5. Add course structure, files in raw material and announce it. This should create a CourseEvent and redirect to course player with 5 tabs, …
=> BaseCourseGroup Implementation

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/adminDashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/collection_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gbase.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gcollection_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/hierarchy_tree.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_details_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/analytics_methods.py, gnowsys-ndf/gnowsys_ndf/ndf/views/trash.py, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
**update PR#1595 - group create, delete with restore feature**
=> updated PR#1595 - group create, delete with restore feature

doc/dlkit-gstudio-impl/read_repos.py, doc/dlkit-gstudio-impl/repository_data_setup.py, gnowsys-ndf/dlkit_gstudio/osid/markers.py, gnowsys-ndf/dlkit_gstudio/osid/objects.py, gnowsys-ndf/dlkit_gstudio/repository/objects.py, gnowsys-ndf/dlkit_gstudio/utilities.py, gnowsys-ndf/gnowsys_ndf/ndf/views/asset.py
Made relevant changes mention in Jeff's [post](https://clix-platform.slack.com/files/birdland/F4526GWTU/get_object_map).
=> get_object_map function implementation

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/nroer_ebooks_entry.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/search_scripts.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/sync_existing_documents.py, gnowsys-ndf/gnowsys_ndf/ndf/models.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/Upload_File.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/data_review_table.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/data_review_tbody.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/data_review.py, gnowsys-ndf/gnowsys_ndf/ndf/views/file.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py, gnowsys-ndf/gnowsys_ndf/settings.py
Run `python manage.py sync_existing_documents` after taking pull.
**Updates**
1. GSystems to have new field:
`legal : {'copyright': '<CC-BY-SA>', 'license': '<GPL>'}`
2. Remove field `license` from GSystem class
1. GSTUDIO_DEFAULT_LICENSE will now be called as GSTUDIO_DEFAULT_COPYRIGHT.
2. New variable added: GSTUDIO_DEFAULT_LICENSE
3. `sync_exiting_documents` to update all existing GSystems.
4. Modify form elements from `license` to `copyright` and saving accordingly.
=> Adding Copyright and License fields in GSystems

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_about.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gbase.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/landing_page_clix.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/registration_base.html
Landing Page
Login Page
Welcome Page 
modified based on New UI
=> Customized Landing Page, Login Page, Welcome Page

gnowsys-ndf/gnowsys_ndf/factory_type.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/asset_content_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/assets.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/explore_2017.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gbase.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/ajax-urls.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/course.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
- Asset and Asset Content form added.
- Asset listing and navigation.
- Separate detail view for asset content.
=> asset and asset_content creation

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
1. Open blog tab and hide 'selection from templates' for blog type page creation.
2. set urls to tabs in course/group dashboard. open tabs and load template based on title
=> Updates in group dashboard

doc/schema_directory/ATs.csv, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/asset_content_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/resource_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_video_player.html
-UI changes for video player.
- some of the unnecessary labels removed from add asset template.
- Provided UI to render HTML and audio mime type files in resource_view template
=> CSS for widget vieo player

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/clix-activity-styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/asset_content_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gbase.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/resource_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_audio_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_video_player.html
Added Video widget with transcript
Video widget with transcript id modified
Save button added and modified in the asset detail form.
=> Widget-Audio/video modified 

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/asset_content_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/assets.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_pages.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_unit.html
Unit create : placeholder, naming and styles
Lesson create: placeholder and name
=> Unit Create/Lesson Create Updated

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/clix-activity-styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/asset_content_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_about.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/explore_2017.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html
'Assessments' added to header
Assessments pointing to OAT
'Create Unit ' updated
Asset detail, Asset Preview modified UI
=> Assessments, Create Course Unit, Asset Detail

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_pages.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/unit_structure.html
Button of activity editor resolved
=> Activity Editor Modified

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/in-line-texteditor.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/landing_page_clix.html
Comment, Feedback button modified
Login button modified
Unit header 
Group section changed
=> Feedback, login button modified

gnowsys-ndf/gnowsys_ndf/ndf/urls/__init__.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/unit.py, gnowsys-ndf/gnowsys_ndf/ndf/views/unit.py
**Added base unit urls and view**
Added url and method for:
- Create/Edit
- List
- Detail
=> Added base unit urls and view

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/js/ckPlugins/addJhapp/plugin.js, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/jhapp_list.html
- `/ost/` replaced with `/openstorytool/`.
- Motion of the earth interactive added at `/rotation/`
=> Urls updated in addJhapp plugin

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/unit_structure.html, gnowsys-ndf/gnowsys_ndf/ndf/views/unit.py
=> Provided edit lesson feature

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/unit_structure.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
- Listing activities except one in current lesson
=> Listing activities except one in current lesson

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/js/ckeditor-config.js, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html, gnowsys-ndf/gnowsys_ndf/ndf/views/unit.py
Added new configurable variable: hide_bannerpic to render/hide the banner picture in views.
configured 'Justify' : alignment class in the editor.
Activity Player: Modified for full width (100 %).
=> CMS Activity Player: UI

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/js/ckeditor-config.js
- Added spellchecker
- Added Font sizes
=> Configured Editor

doc/schema_directory/ATs.csv, gnowsys-ndf/gnowsys_ndf/factory_type.py, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/js/ckPlugins/addJhapp/plugin.js, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/asset_content_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_about.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_pages.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_unit.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/jhapp_list.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_metadata.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/audioDashboard.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/imageDashboard.py, gnowsys-ndf/gnowsys_ndf/ndf/views/trash.py, gnowsys-ndf/gnowsys_ndf/ndf/views/videoDashboard.py, gnowsys-ndf/gnowsys_ndf/settings.py
- Run Kitty Run and Physics video player button added on Tools page.
- Instead of purge now asset content will be delete.
- Cancel button added on Metadata page.
- Validation on upload alternate file.
- New RT has_admin_page and new AT player_discussion_enable added
Run fab update_data command
=> New Interactive tools added and bug fixes related assets

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/dump_users.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/group_export.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/schema_mapping.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/sync_existing_documents.py
Updates are as follows:
- Introduces multiprocessing for faster dump.
- logic changed for fetching data from triple
- removed dual queries for each object by redesigning the workflow.
- made functions more modular.
- added docstrings to all the functions.
- A clear inputs to start dump.
- Exit calls added accordingly.
- Initialised users dump also.
Modified `sync_existing_documents.py` : 
- Update `legal` field for Group, Author and File instances.
=> Updates in dump(export) script

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_page_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_node_form.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_tags.html
- Add Asset form modified
- Tags modified in add_asset and in Activity Page
=> Tags & Asset Modified

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/asset_content_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_about.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_pages.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/translation_list.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_tags.html
- Course_about description modified to full length.
- Course_about: Tags placement modified.
- Tags 'Uppercase' removed.
- Group_header: setting icon modified.
- Asset_content_detail:  Removed 'Uppercase' from Asset desc.
=> UI Misc changes

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_page_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_pages.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/unit.py
=> Error on edit activity.

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/assets.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_pages.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/in-line-texteditor.html
- Activity Alt Lang Page modified
- Icons for Buttons added in Asset_content detail, add_asset, Course_pages
- 'Settings' modified to 'Options' in asset and course pages
- '*' color changed to red
=> UI Modifications

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_pages.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/translate_form.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/unit_structure.html
- Mathjax not loading on activity player fixed.
- gstaff access to action buttons for activity
=> Bugs regarding mathjax

doc/dlkit-gstudio-impl/assessment_lookup.py, gnowsys-ndf/app_configs/configs.py, gnowsys-ndf/app_configs/registry.py
**Made config changes for assessment service running in dlkit_gstudio with AUTHZ**
- Replaced `MONGO_1` adaptor with `GSTUDIO_1` 
- Opened managerial paths for Assessment Service for gstudio.
=> Made config changes for running assessment service in dlkit_gstudio with AUTHZ

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/dump_users.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/group_export.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/group_import.py
1. Dump script updated: add fetching contributors call for filehives in try-except block.
2. Validating data-dump before restore using checksum. 
3. Reading config variables.
4. Restoring user objects with validations against existing users.
5. Close file-open object on exit or on finishing.
6. In user-dump check if email exists else pass username
=> Initial phase of Restore script.

doc/deployer/Migrating_SQLite_DB_to_PostgreSQL.txt, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/dump_users.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/group_import.py
1. Parse the `users_dump.json` file generated while `group_export`.
2. Check on target-system whether user with same `id` exists.
3. If yes, check whether the username is matching. If yes, check if email-id id does not exists, then add the one from the dump. This user already exists in target-system.
4. If user from step2 is not found OR username does not match, create a new user with all the fields passed in the `json` structure, also create a corresponding author object for this user and then update the json with new fields `new_id` and `new_author_id`, to maintain a record of change in ids while restoring the nodes and its values where user ids are involved.
=> Dump-Restore: User objects restoration defined.

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/group_export.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/group_import.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/schema_mapping.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/sync_existing_documents.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/users_dump_restore.py, gnowsys-ndf/gnowsys_ndf/ndf/rcslib.py, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/simple_filters.py
Maintain global variables: `dictionaries` for `USER_ID_MAP` and `SCHEMA_ID_MAP` which will hold ids of dumped objects [from source] as key and new generated user-id, target machine's schema objects' objectId as value.
Till this implementation of User and Schema mapper functions get successfully completed.
=> For Restore: maintain mapper for user-ids and factory objects Ids.

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/group_export.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/group_import.py, gnowsys-ndf/gnowsys_ndf/ndf/views/utils.py
- The restore script is now in test phase. Most of the functionality is implemented.
- Include group-node in dump script
- Added 2 new utility functions:
- `replace_in_list(list_to_update, old_val, new_val, append_if_not=False)`:  Replace <old_value> with <new_value> in list_to_update, if exists. Else if append_if_not flag is passed True. add the <new_val> in list_to_update
- `merge_lists_and_maintain_unique_ele(list_a, list_b)`: Merge 2 lists list_a and list_b and remove     duplicate elements and return the result list.
=> Restoration of data dump using rcs files

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/clix-activity-styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/opensans-fonts.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/card_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/explore_2017.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gbase.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/get_info_pages.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/horizontal_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/module.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/module_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/views/module.py, gnowsys-ndf/gnowsys_ndf/ndf/views/unit.py
- Module List updated with new UI and Module Card
- Module Detail's edit updated.
- Save Lesson, resolved
=> UI changes and Data Binding for Module cards

doc/developer/Dump-Restore.org, doc/developer/Group_migration.txt, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/group_export.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/group_import.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/sync_existing_documents.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/utils.py
1. Group import script updated to maintain datatypes of values, mainly datetime
2. Documentation added for dump-restore calling it as Group_migration. Archived old doc
3. sync_existing_documents updated to prevent failure on clean db, i.e first run
4. setting default action as fork on group-dump
=> Updates on Group restore, sync_existing and misc fixes.

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/assets.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_tags.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
1. Marking and un-marking an asset as Raw-material
2. Styling added for raw-material badge on asset card
=> Asset as Raw-material

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html
1. show unit actions only to gstaff
2. Show lessons on hover of `Export to ePub` action
3. Highlight lesson name on hovering over a lesson
=> Export option UI updated

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/card_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/explore_2017.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/explore_secondary_header.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header_clix.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/horizontal_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_explore.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/explore.py, gnowsys-ndf/gnowsys_ndf/ndf/views/explore.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/module.py, gnowsys-ndf/gnowsys_ndf/ndf/views/unit.py
1. Show profile-pic/banner-pic thumbnail in card_group. [group and unit listing cards]
2. Second level header redesigned.
3. Implemented `Enroll` option for LMS.
4. Updated menu for mobile view [remove 'new' ] and change `Explore Project` to 'Explore' in header.
5. Apply hyperlink for full horizontal-card (module card)
6. Updated `lms_explore.html` to list modules and units.
7. Displaying list of modules for unit-create bug fixed.
8. Display units under a module based on logged-in users role.
9. Updated views for explore tabs `Drafts` and `Courses`
=> Updates for Explore and LMS

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/card_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_about.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gnotebook.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_explore.html, gnowsys-ndf/gnowsys_ndf/ndf/views/page.py
1. Disable prev-next in activity player based on current activity
2. Display altname if, on card-group
3. Settings action for announced unit
4. Blog page creation from announced unit	
5. Hidden translate from player and hide filters from notebook
6. Made notebook full screen
7. styling for player updated
=> LMS Updates

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_about.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_explore.html
- Overview and Lesson tab restyled to make full screen
- Overview modified with icons
=> Lms-Explore 

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_enroll.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_user_access_modal.html
New widgets created:
1. Enroll btn added as a separate widget template
2. Access control modal added as a widget.
=> Widgets templates added

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/asset_content_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/explore_2017.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/in-line-texteditor.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_dashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/module_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
- Hiding embed tools  appearing in the editor (comment/feedback) which is used for 
authoring.
- Changed redirection of i2c gallery page.
- Enrollment in a unit is leading to both Unit and Module card getting displayed in My Courses. Only Unit should be displayed.
- Validation on create/edit module and create unit.
- Title not visible while in detail view of resource or gallery issue.
=> LMS Issues.

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/card_group.html
- Added course status  In-Progress,Completed and Upcoming on Unit cards.
=> Unit status on card

gnowsys-ndf/gnowsys_ndf/ndf/models.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/card_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header_clix.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/help_page.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_dashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/__init__.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/user.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/home.py, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py, gnowsys-ndf/gnowsys_ndf/settings.py
- Showing total points from unit on cards.
- On click of unit card showing full progress report.
- Added condition for help page.
=> Added My Performance tab in LMS

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/sync_existing_documents.py, gnowsys-ndf/gnowsys_ndf/ndf/models.py, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/card_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header_clix.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/help_page.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_dashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/rating.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/user_course_analytics.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/__init__.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/user.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/asset.py, gnowsys-ndf/gnowsys_ndf/ndf/views/explore.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/home.py, gnowsys-ndf/gnowsys_ndf/ndf/views/node.py, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py, gnowsys-ndf/gnowsys_ndf/settings.py
**Updates**
1. Analytics w.r.t a Unit implemented.
2. Course completion status implemented. 
- On course content tree, highlight the visited activities and mark a `Lesson` Complete or Inprogress accordingly.
3. Prevent self-rating i.e contributors for rating.
4. Prevent loading info pages in activities while adding into lessons.
5. Updated counter functions for user actions.
6. Progress bar updated for completion of total and completed lessons and activities
**Model level Updates**
1. New fields in Counters:
a. `visited_nodes` = `list` 
*  [str(`ObjectId`): `int`] where `ObjectId` will be Id of node whose detail view has been visited by the user, irrespective of the context. The value `int` represents the number of time the user visited.
b . `assessment` = `dict`
*  `'assessment': { …
=> Analytics for Course

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/js/ckPlugins/addJhapp/plugin.js, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/asset_content_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/jhapp_list.html
- File preview was not happening if Resources/Gallery.
- Removed motion game from interactives listing
=> File preview in Resoucres/Gallery

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/group_export.py, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/js/ckPlugins/addJhapp/plugin.js, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/explore_secondary_header.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gnotebook.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header_clix.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_node_form.html, gnowsys-ndf/gnowsys_ndf/ndf/views/explore.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
1. Counter methods: removed delay. Breaking of Notebook, RawMaterial and Gallery handled
2. Make node name mandatory for widget node form. Check note creation
3. Show public and private groups to admin from Projects
4. Hide projects for students and anonymous users.
5. Editor open bug fixed
6. Note create styling in LMS updated.
7. Assessment Iframes updated.
8. Remove My Dashboard link from header username link
=> Misc and LMS Bug fixes

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/asset_content_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header_clix.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/help_page.html, gnowsys-ndf/gnowsys_ndf/ndf/views/home.py
- Added scstyles css to help page template.
=> Help  Page CSS

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/group_export.py, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/asset_content_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header_clix.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/in-line-texteditor.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/user_course_analytics.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/__init__.py, gnowsys-ndf/gnowsys_ndf/ndf/views/home.py
- Created by name showing only in CMS.
- Close button added on user analytics overlay.
=> Misc. Issues

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/in-line-texteditor.html
- Enrol button modified 
- Post button modified
=> Misc UI changes 

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_pages.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/in-line-texteditor.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/discussion.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
- Showing available activities in different languages.
- Remove delete files option from create Resource/Asset and Folder.
=> Translated pages Rendering in activities.

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/clix-activity-styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/translate_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/translation_list.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/unit_structure.html
- Added light background gray
- The activity player of the CMS made full screen
- Alt lang detail page, made full screen, aligned the top margin.
- Secondary header , UI changed in Sticky and normal.
=> UI Modifications for CMS 

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_page_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
- Added alt name field in create/edit activity page form.
- Alt name will be mandatory.
=> Alt/Display name for activity page.

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/buddy.html
- Resolved Buddies rendering issue
=> New Buddis

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/sync_existing_documents.py, gnowsys-ndf/gnowsys_ndf/ndf/models.py, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/js/ckPlugins/addJhapp/plugin.js, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_unit.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/explore_secondary_header.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/group_pages.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header_clix.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/jhapp_list.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_node_form.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/translation.py, gnowsys-ndf/gnowsys_ndf/ndf/views/unit.py
- Added new field project_config as dict in Group Class.
- Fetching existing Grelations while creating new translations.
- Added display name field in translation form.
Please Run sync_existing_documents
=> project config field in group.

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/sync_existing_documents.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_about.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/in-line-texteditor.html, gnowsys-ndf/gnowsys_ndf/ndf/views/discussion.py
- `project_config` field added in Author Class.
- sync_existing_documents updated as per new query.
- Group Analytics visible to Group admins and gstaff_access users.
- Progress Report visible to authenticated and enrolled users only.
- Showing delete option in comments for group admins
Please do `python manage.py sync_existing_documents`
=> Query update in sync_existing_documents.

doc/deployer/del_has_thread_update.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/create_schema.py, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
Refer #1751 Issue.
Run `execfile('../doc/deployer/del_has_thread_update.py')` in shell
=> Interactions visibility

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_unit.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header_clix.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/unit_structure.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/unit.py, gnowsys-ndf/gnowsys_ndf/settings.py
- added `GSTUDIO_EDIT_LMS_COURSE_STRUCTURE` in settings to show/hide Edit Course Structure button in LMS.
- Default values for tab_name,section_name and subsection_name added.
=> Section,Subsection UI binding.

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/card_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_about.html
- Showing tab/lesson name on overview.
=> Course Overview (LMS) 

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/group_export.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/group_import.py, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_enroll.html
Updates:
Handle Restoration when user-dump not available. Set `DEFAULT_USER_ID` and use of flag `DEFAULT_USER_SET` for updating the node's fields.
=> Restore script upgraded.

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/footer_clix.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gbase.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/landing_page_clix.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_dashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
- footer added in gbase.
- appears on cms/lms except activity player.
- Landing page modified css and footer
=> Footer addition

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/js/ckPlugins/addJhapp/plugin.js, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/jhapp_list.html
- RKR's Hi and Te version added.
=> Tools list updated.

gnowsys-ndf/bower.json, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/basecourse_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gcollection_ajax_view.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gcourse_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gcourse_units.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/quiz_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/group.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py, gnowsys-ndf/gnowsys_ndf/ndf/views/quiz.py
Updates:
1. Load Quiz player only for authenticated users otherwise display message with login link.
2. Provision to add `QuizItemEvent` and `QuizItem` in course authoring.
3. Quiz-player updated to use fields : `quizitem_max_attempts`, `quizitem_show_correct_ans`
4. Display All QuizItem and QuizItemEvents based on Group type in Quiz App. [`<domain>/<group_name_or_id>/quiz`]
=> Updates on Quiz module

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/user_interactions.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/ajax-urls.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/discussion.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/discussion.py
Visit: `<domain>/<group_id_or_name>/discussion/replies/<username_or_user_id>` to view user specific interactions in a Group
=> Interface to display Users Posts[Replies] in a group

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gcourse_event_group.html
**Updated background color for i2c courses. Fixed bug of i2c course banner image.**
=> Updated banner background color for i2c courses. Fixed bug of i2c course banner image.

gnowsys-ndf/gnowsys_ndf/ndf/urls/__init__.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/tools.py, gnowsys-ndf/gnowsys_ndf/ndf/views/tools.py
- urls and view added for tools data logging.
- Use `/tools/logging` to write captured JSON data on file system.
- All the captured data files will be store in `/data/gstudio_tools_logs/<tool_name>/<language>`.
- Each file name consist of user_id. For ex. 1.json.
=> Data logging for Tools

gnowsys-ndf/gnowsys_ndf/ndf/management/commands/teacher_agency_type_update.py, gnowsys-ndf/gnowsys_ndf/ndf/models.py
Run `python manage.py teacher_agency_type_update`
Updates:
1. Allow gstaff access if user's author obj has agency_type=Teacher
2. teacher_agency_type_update script added.
=> Admin access to Teacher users

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_pages.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/get_info_pages.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/unit.py
- Showing translated page for info page if available.
- CSS not loading for ratings widget fixed.
- Showing Teacher's page for group admins an super users
=> Translations for info pages.

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/js/ckPlugins/addJhapp/plugin.js, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/horizontal_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/test_template.html
- Added a tree structure for curriculum structure in test_template.html for workspace implementation
- Section 
- Sub-Section 
- Sub sub-section 
- Topic [leaf node] added
- The tree structure is not limited to any number of sub section and stops only at topic. 
- Cannot be saved without a name.
=> Workspace Curriculum tree UI

doc/deployer/set_threads_prior_nodes.py, doc/deployer/unit_assessments.py, gnowsys-ndf/gnowsys_ndf/ndf/management/commands/unit_assessments.py, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/quiz_player.html, gnowsys-ndf/gnowsys_ndf/ndf/views/discussion.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
**Imp**: Run `python manage.py unit_assessments` _OR_ `python manage.py unit_assessments <https://domain_name> y` to parse through all the OAT assessment iframes from the content of the Unit>Lessons>Activities and store them as value in GAttributes with Units.
Updates:
1. Quiz-player to have purple action buttons to match the layout.
2. Points on commenting bug fixed.
3. Maintain parent-node' `attrtibute_set` while cloning(announcing).
=> Comments Points Bug fixed. Quiz-player UI updated. New Script in commands

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/user_course_analytics.html, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
Updates (Refer to the sample screenshot attached below):
1. Displaying incorrect status for Lesson and Activity Completetion status progress bar bug fixed
2. UI for User-analytics updated. [Structure alignment]
3. On Assessments `Update`(`load-assessment-analytics`) under progress report, will now update User-points as well.
Sample screenshot:
=> Updates in User-analytics rendering

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/horizontal_card.html
- Module card css updated 
- text above image
=> Module Cards Css 

gnowsys-ndf/gnowsys_ndf/ndf/models.py, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_about.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_dashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/user_course_analytics.html, gnowsys-ndf/gnowsys_ndf/ndf/views/assessment_analytics.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
Updates:
1. Fields fetching for assessment analytics: 
1. Total Questions
2. Attempted Questions
3. Correct Answers
4. InCorrect Answers
3. Not Attempted
2. Create GAttribute `total_assessment_items` iff the assessments in the unit exists.
3. User-analytics modal UI updated
4. Prevent closing of User-analytics modal on `ESC` press and outside modal click
=> Assessment analytics and UI updates

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header_clix.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/landing_page_clix.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/module_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_enroll.html, gnowsys-ndf/gnowsys_ndf/ndf/views/home.py
- Redirecting to landing page if clicks on logo in header.
- Validations on settings button in module detail.
- Changed label `Join` to `Enroll` if not workspace.
=> Redirection to landing page and validation on Module detail.

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/in-line-texteditor.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/quiz_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/user_course_analytics.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/assessment_analytics.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
Update counters of Buddies, on `Update`  in progress report w.r.t Assessment Analytics
=> Assessment analytics updates for Buddies

README.md, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html
- Banner image made full width
- It is responsive 
- the aspect ratio is maintained
=> Banner Image 100% width

gnowsys-ndf/gnowsys_ndf/ndf/views/tools.py
- Fixed tool's data logging if user logged in with buddies.
- Problem of multiple data entries in new buddy's json.
=> Tool's data logging.

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_enroll.html
- Added tooltips for unit detail (lms secondary header).
- Enroll all: button updtaed (Made more prominent).
=> tooltips and Buttons

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss
- responsive query for the Unit name in activity player header 
- Test at 1024px, 1440px,1630px, 1880px and above
=> Media query for activity player header

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html
**To Test:**
- If on first activity of the lesson, _previous lesson_ active, else should be **disabled**
- _Next lesson_ will be active only on the last activity of the lesson.
=> Navigation: activity player header

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_page_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_unit.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_explore.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_metadata.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_node_form.html
- Cms: Cancel and save button uniform throughtout
- All unit cards clickable, removed prevent_click-True
=> Misc Css changes

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/translate_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/views/translation.py
- translated page edit is configured with cancel button, it redirects to the translation page detail view.
=> cancel_url for translated pages edit

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_page_create_edit.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_pages.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/unit.py
- Activity, assets and assessments tabs in LMS view
- Css for tabs (reverted color)
=> Master merge lms cms

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/asset_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/asset_content_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html
- Asset tags/ cards UI improved
- Asset detail: made center aligned and actionable on the left. 
- Add asset, new UI
=> Asset management UI

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_pages.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/horizontal_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html
1.  Verified condition based on site name for Coordinator's page and Pages
2.  Orange-button-template css added for activities
3.  Edit metadata form updated
4.  metadata readonly: for normal user and non-group admins, else edit metadata option visible.
5. Actions visible to all; Edit and Add metadata disabled for non-group admins
=> Metadata: Edit and View based on user authority

gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
- Enabled metadata widget for AssetContent also.
- Given metadata of assets will be applicable for associate AssetContent.
=> Metadata widget

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header.html
Explore url in nroer instance added to create a course or a workspace.
=> Explore Url added to the top header

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_about.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/footer_clix.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gtask.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_dashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/views/event.py
Linking of calendar tasks  with task details
=> Calendar Binding task

requirements.txt
Updated `dlkit` version to `0.5.17` and removed unnecessary qbank requirements from gstudio `requirements.txt`
=> Reflected updated requirements from qbank to gstudio

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/images/Transcript.svg, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_audio_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_video_player.html
Transcript icon added to audio and video transcript toggle buttons
=> icons added

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/curriculum_hierarchy.html
Added the search-box to sub-sections in topic-map.
Added the Javascript function -search_func() , which starts searching the sub-sections list after entering a letter in the search-box. It converts all the strings and input characters into uppercase for efficiently searching the list. It makes use of the attribute "data-topic" for searching.
=> Search widget for sub-sections in topic-map

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/footer.html
Sitemap link is added on footer
=> Sitemap link is added

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/images/metaStudio-profile.svg, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/images/metaStudio-profileold.svg, gnowsys-ndf/gnowsys_ndf/settings.py
metastudio logo color  is edited on header
=> metastudio new logo-size changed

gnowsys-ndf/conf/locale/hi/LC_MESSAGES/django.po
PO file compiled successfully for hindi language.
=> Po file generated

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/buddy.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html
- New colors for the primary header and secondary header.
- Dropdowns colors fixed.
- All buttons made of the same color.
- Activity player sidebar (index of all activities) made collapsible.
- Dynamic height assigned to buddy bar.
- Sav and cancel button for 'Add buddy overlay', provided on top and bottom both.
- Removed the alert message for displaying the list of the current/active buddy.
=> March Release changes

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/explore_2017.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/explore_secondary_header.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_explore.html, gnowsys-ndf/gnowsys_ndf/ndf/views/explore.py
If modules sort list is not defined, by default display all modules.
On modifying module sort list, delete existing GAttribute and create a new one.
=> Sorting Modules bug fixed

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/clix-activity-styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/horizontal_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_explore.html
A. Module card updates:
1. Replace description of module with its name on card
2. Name of card to follow theme color
3. Increased font-size of metadata on module card
4. Replaced "Grade" with "Class /Grade"
5. Class/Grade values not to show "Grade" as string in values
B. Activity player udpates:
1. Icon added for Collapse LMS index (on lhs)
2. Icon to toggle to depict close-open actions
3. Scroll up to selected Activity/Page if lesson index is long
4. Transcript button's color changed from blue to theme color
C. Alignment of Modules and Units listings in Explore moved to right slightly.
=> UI updates

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/images/Transcript_v1.svg, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/asset_content_detail.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header_clix.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/in-line-texteditor.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_dashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_audio_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_video_player.html, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
- `Contributed by`  visible only if workspace and draft unit.
- `File Size` visible in file detail view.
- `My workspace` added in my desk.
- Icon for `Transcript` and `Comments` updated.
- URL  reference after login.
=> LMS UI bugs/features

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/module_detail.html
- Notebook:  create new, aligning filters and name to be title
- Post Testing Fixes #1884 (Merge from beta)
- Lessons and overview combine
- Configurable Tabs: Secondary Header #1893 (Merge from beta)
- Course listing + Analytics binding + Default user workspace and My desk added #1866 (Merge from beta)
- Full width activity player
- Notebook tab renamed as e-Notes
- Activity player:
- Secondary header: color change on hover
- Unit name increased Fonts
- Primary Header:
- language dropdown: css updated for hover on dropdown.
=> Release Taks

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_unit.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gnotebook.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/unit_structure.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_node_form.html, gnowsys-ndf/gnowsys_ndf/ndf/views/unit.py
- Notebook: name replaces with Title, Create new appended with +, Filters alignment. PR #1884 merged from beta
- Configurable Tabs: Secondary Header #1893 (Merged from beta)
- css fixes for lms secondary header, module detail
=> Cherry Picked from Beta and merged with Master 

doc/schema_directory/ATs.csv, gnowsys-ndf/gnowsys_ndf/factory_type.py, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/card_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_dashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_user_profile.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/__init__.py, gnowsys-ndf/gnowsys_ndf/ndf/views/quiz.py, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
Run `fab update_data` afetr taking this pull
Updates:
1. New AttributeType: `organization_name`
2. User dashboard with `Edit Profile` link beside username
3. widget for User profile data displayed below username in dashboard
4. User profile form 
5. Validation of form field inputs
6. Saving of form using ajax and refreshing widget for User profile data
=> User profile widget 

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header_clix.html
Clix font resizer fixed
please close previously generated  pull request for same task and merge this pull request instead of that.
=> clix font resizer fixed

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/js/ckeditor-config.js
- Find & Replace ,Underline,  Smiley,Undo & Redo plug-ins enabled for ckeditor(All toolbars)
=> Plugins for ckeditor

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html, gnowsys-ndf/gnowsys_ndf/ndf/views/unit.py
- Added padding between ratings/comments area and activity content.
- Back button  for lesson/section listing fixed.
- All navigation button's z-index issue fixed.
- `e-Notes` added as default text for notebook app if base_unit or announced_unit.
Note: Previously notebook was called as blogs in case of base_unit and announced_unit hence, after this code update, Unit's configuration needs to change accordingly to e-Notes.
=> Activity player UI fixes.

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/user_course_analytics.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/course.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
- Added progress report tab in unit.
- CSS needs to be fixed.
- Superuser will see all member's /Student's progress report unit wise, and individual member can see their progress report unit wise
=> Progress report as a tab in Unit.

gnowsys-ndf/bower.json, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_about.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_dashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/user_course_analytics.html, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
@Prachirb @saavrabh The progress-report template has been reset due to css distortion.
Also, group-analytics is not loading. Please address at your convenience.
Run `bower install`
=> Provision to Progress-report download as PDF

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/curriculum_hierarchy.html
-Added the Prerequisite tags.
-added foundation accordion for the topic-list and search bar.
- added the prerequisite labels in the subsection-view-area.
- Fixed minor UI changes.
-changed button names.
=> Redesigned the Topic-map form

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/curriculum_hierarchy.html, gnowsys-ndf/gnowsys_ndf/ndf/urls/__init__.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
- `has_prerequsite` RT added for `Topics` in factory_types.
- Please run `filldb` & `sync_existing_documents` once code merge.
=> Prerequsite UI binding in topic map

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gnotebook.html
1. All Notes/All Blogs renamed to `Other's Posts`
2. My Notes/Blogs renamed to `My Posts`
=> Notebook Tab Name 

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header_clix.html
1. Activity player header,  hover properties modified.
2. Collapsible index-content overflow for medium screens resolved. 
4. font for 'back/lessons' made same as other tabs.
5. Language and Logout dropdown on the top header was hidden behind activity player's header: Resolved.
6. Top header hover properties and logo display made neat.
=> Activity Player Changes

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gnotebook.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html
1. Url for assessments tab renamed 
2. Write Note in activity player renamed to e-notes
3. Unit name spilling over in 1024px screen handled 
4. Notebook filter spilling over 1024px 
5. Hidden deactivated tabs in activity player 
6. Misc css
=> Release Changes 

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/card_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/partner_showcase.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/translation.py
partner listing with card-group.html 
misc changes
=> Misc changes required for nroer

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/card_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/main_simple_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/partner_showcase.html, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
activity player css fixed
grid problem for partner showcase card resolved
error in get_lang_node fixed
=> minor fixes in activity player, partner showcase

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_about.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_content.html
- Overview accordion added above lessons
=> Accordion added above lesson showing overview

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gnotebook.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/note_page.html
1. UI updates for Notebook tab content that includes:
- icons changed
- active and hover colors changed
- font-size for creator information reduced
2. Show `Results` for quiz only to gstaff members
=> Notebook Updates

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/clix-activity-styles.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html
Updates:
1. Maintain theme colour for activity-content
2. New styling added and moved existing CSS from activity-player template
3. Activity-player full screen on toggle LHS index; variable names redefined following conventions
=> Activity-player updates

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_content.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_enroll.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py, gnowsys-ndf/gnowsys_ndf/ndf/views/asset.py, gnowsys-ndf/gnowsys_ndf/ndf/views/discussion.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py, gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py, gnowsys-ndf/gnowsys_ndf/ndf/views/node.py, gnowsys-ndf/gnowsys_ndf/ndf/views/ratings.py, gnowsys-ndf/gnowsys_ndf/settings.py
Set `GSTUDIO_IMPLICIT_ENROLL = True` in local_settings.py after taking pull.
Implemented as per [discussed requirements](https://gist.github.com/katkamrachana/a9707bba85583c35091040ea480f2bbb#a-enroll-the-user-and-create-counter-object-on-following-actions)
=> Implicit Enrollment

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/card_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_dashboard.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
Displaying module name in unit-card
=> Unit-card layout updated

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/explore_secondary_header.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/horizontal_card.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_photo_upload.html
**Updates:**
- second header indented
- apply default banner for author groups as well
- module card icons to be in theme color
- defined global variables making it easy to modify theme-color
- increased width of unit-card
- title on unit-card font changed
=> UI/UX Updates

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/footer_clix.html
=> Spelling updated

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html
**BUG REPORTED:**
In health and disease module multiple copies of activity is rendered recursively within the same activity.
**SOLUTION:**
Changes made in the JS of activity_player.
=> Resolving page recursion issue

doc/release-scripts/18.11.r1.patch.md, doc/release-scripts/fix_notabletodraw_painturl.py
**Modified patch document 18.11.r1.patch.md**
---
+ Imported steps to include the `turtle_customized_version` i.e. customized version(few features) of turtlelogo instead of full version.  
+ In Survey, executing following sync_users command to sync the users of sp99 and sp100:
`python manage.py sync_users /home/docker/code/user-csvs/sp/sp99_users.csv`
`python manage.py sync_users /home/docker/code/user-csvs/sp/sp100_users.csv`
=> Modified Patch document.

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/help_videos.css, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gbase.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/video_sidebar.html
**Task:**
New help videos assisting students regarding the working of the CLIx platform are to be added.
**Solution:**
- Created new template video_sidebar.html to have a drop-up menu displaying the help videos.
- Created new stylesheet help_videos.css to style the drop-up menu.
- Modified gbase template to include template for help videos.
**File Changed:**
gbase.html                     Line No:68
**Files Added:**
- video_sidebar.html
- help_videos.css
=> Addition of Help Videos

doc/data-restoration.md
Modified `data-restoration.md` for data swapping.
=> Added steps for data swapping.

doc/script_to_find_existing_authored_assessment_links.py
**Script for finding the existing authored assessment links**
---
+ python script to fetch the existing authored assessment link of the given Assessment_Offered_Id.
=> script pertaining to find existing authored assessment links

gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/clix-activity-styles.css, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_content.html
- The transcript having double scroll issue is solved 
- Overview section in Units , icon added to show its toggle section
=> The transcript double scroll issue and Overview icon added 

doc/release-scripts/template_addition.py, gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/js/slider.js, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gbase.html
**Requirement:**
Template to add images that reflect as sliders/carousels.
**Solution:**
- Inclusion of script that triggers creation of template for sliders, that can be accessed for authoring.
**Files Created:**
- template_addition.py
- slider.js
**File Changed:**
- gbase.html                     Line No:52
=> Inclusion of Sliders

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_content.html
**Style changes done for the overview section of course content page**
---
-Issue : The toggle icon of the overview section is not reflecting the corresponding action.
-Fix     : Have attached class name ` dake ` and id `click_advance ` to the button tag and have written respective inline js for the same. 
` $('.dake').click(function() {
$("#click_advance", this).toggleClass("fa fa-angle-up fa fa-angle-down");
}); `
=> Overview section icon toggle ( js use)

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_assessment_data.html, gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gcourse_event_group.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/urls/course.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
---
+ Defined url `/course/assessment_data` and  a view function `course_assessment_data` which accepts `activity node` as input to extract the Assessment_Offered Ids pertaining to the activity.
+Defined a function `get_assessment_results` to fetch the Assessment-Takens based on Assessment Offered's.
+course_assessment_data returns the assessment results of the particular user, which includes the student_id , Question_text, Response submitted by the user, Assessment_Start_time, Response_submission_time.
=> Assessment Report Creation

gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html, gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py, gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
---
+ Included language nodes 'hi' and 'te' in `course_assessment_data` function.
+ Defined a list `node_assessments`
+ Defined a function `get_offered_id(node_id)` to retrieve the offeredId's of the language nodes : en, hi and te. 
+ Appended 'en' , 'hi' and 'te' OfferedId's to the `node_assessments` list. 
few use-case taken care of:
- offered Id's of 'en' , 'hi' and 'te' nodes are different . 
- offered Id's of 'en', 'hi' and 'te' nodes are similar for some assessments
=> Assessment Results display in Hindi and Telugu
