gnowledge/gstudio

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/collection_ajax_view.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
***Breadcrumbs implementations***
* For maintaining the navigation path in collection hierarchy implemented breadcrumbs on top of collection hierarchy
* Breadcrumbs will only be visible for collection navigation.
* As soon as you clicked an item in collection hierarchy in left panel, its details view will rendered on page body and breadcrumb will set for that clicked node. Which will maintain the navigation path from previous clicked nodes in collection. 
* When you click on breadcumbs the breadcrumbs list will also be manipulated and rendered.
* Ajax call placed on click of collection elements to manipulate breadcrumbs list and renders the details of clicked on page body
* ```collection_nav()   --> in ajax_views.py```  takes the clicked node and renders its details on page …
> Breadcrumbs implemented for collection navigation

- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_metastudio_styles.scss
- gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
- Previously background highlight color of selected top-level menu item was black.
- Which was making hard to identify current active top-level menu.
- Which is now made near to current theme's color by making changes in ```SCSS``` file.
- Also commented ```print``` statement in ```ajax_views.page_scroll```.
> NROER: Top Level App bar active background-color changed

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html
D3 collapsible graph has topic as a leaf nodes. On click of which it suppose to go to particular topic. Which is now implemented.
**Check:**
1. Go to ```Repository``` > ```Curated Zone```
2. Select theme and then click on ```Collapsible Tree```
3. Click on circles till leaf-nodes (hollow/White colored) appears.
4. Now click on any of the leaf node. It will take you to particular topic in the new tab.
> Added hyperlinks to topic-leaf nodes of D3-collapsible graph

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/collection_ajax_view.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html
**Showing original-resolution Images on click of mid-size images:**
- The images in file detail view of page was not clickable and it's not with original dimensions.
- Now functionality has been added on-click of mid-size image in file-detail view:
- Will take you to full size image in the same tab.
- This full size image is with it's original dimensions.
- (Before clicking) On hover over mid-size image, it's borders glows up (indicates it's clickable).
- This functionality is also added for mid-size images in the image-collection (Image gallery).
**Alternate colors of the collection listing (displayed on LHS):**
- Now collection list is displayed with alternate colors.
- This will remove the ambiguity while reading long names.
> Images shows their original-size-fullscreeen on click of mid-size image

- gnowsys-ndf/gnowsys_ndf/ndf/views/languagepref.py
Throws following error while setting the preferred language from top-menu bar.
*ValidationError: agency_type does not pass the validator <lambda>*
Check is added in language_pref.py to check the agency_type filed of author if it is empty then sets to default value "Other".
> Bug fixes while setting the preferred language

- gnowsys-ndf/gnowsys_ndf/ndf/views/event.py
As same view is used to editing the generic and specific event types(classroom and exam session) 
because of this, error of using variables before assignment was arising 
Fixed the bug
> Fixed bug in generic event

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/group.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/home.py
previously when we click on the drop down list it was redirecting us to the dashboard of the (i.e the page with banner pic ) and on click of dashboard on the menu bar it was redirecting to the information page of the group
the changes are as follow:-
on click of group name from the drop down list of the menu bar it would redirect to the information page
the dashboard indication with home icon on the left hand side of the second menu bar is replaced with activities 
on click of this it would redirect you to the page with the banner
information page i.e page with the description about the group is made the landing page instead of page with banner pic when we open site user would land on group information page
> drop down list and dashboard url changed

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/groupdashboard.html
- gnowsys-ndf/gnowsys_ndf/ndf/urls/__init__.py
**The links for the group's in *NROER* menu changed**
- Previously, it was redirecting to group's dashboard.
- Now it's redirecting to group's detail view.
- Re-arranged and commented unnecessary urls.
- Changed the icon of the activity link on LHS (as decided in meeting).
--
**Check:**
- Click on any of the two level group header links.
- And watch for it's redirection, if it's redirecting to group's detail page.
> Changed all the group-landing page's link for NROER

- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
- Previously, query was fired without checking argument is object-name (of data type string) or ObjectId.
- This bug is fixed. And checking has been added.
> Bug in user_access_policy() method of ndf_tags.py is resolved

- gnowsys-ndf/bower.json
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/videoDashboard.py
- This plugin gives better controls than default HTML5 player.
- Big play button at center.
- In future we can further customize it.
--
**Install bower dependencies**: ```bower install```
--
**TEST**:
- After installing bower dependencies, go to video resource detail page and try this player.
- For the first time it doesn't show progress bar, but for subsequent play, it shows it and allows you to interact with it.
> Implemented HTML5 video player plugin

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/rating.html
- Bug due to long precision float no being passed to jQuery selector is fixed.
- Long precision float rating is fixed to 2 decimal places.
> JS Bug in ratings is resolved

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/e-library.py
- Top level `Home` link removed.
- Query for getting `E-Library` resources is modified to show only published items.
> NROER: home link removed and e-library query modified

- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
**NROER: Gapp - 'Curated Zone' for 'Groups' will not be available:**
- As per new update/suggestion from Vidya mam, `Curated Zone` in `Groups` will not be available.
> NROER: Gapp - 'Curated Zone' for 'Groups' will not be available

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/new_create_batch.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/videoDashboard.py
On click of Add batch twice , followed by 'Save' click, created an empty batch. This has been fixed now.
Frequent error in get_video_thumbnail() of list index out of range is also fixed.
> Auto Empty batch creation error fixed

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html
**NROER: Gapp bar modified for 'Groups' and 'Partners':**
- Now `Repository` will have following apps:
- `Curated Zone`
-  `eLibrary`
-  `eBooks`
-  `eCourses`
-  Events
- `Partners`, `Groups` will have following apps which is `DEFAULT_GAPPS_LIST`:
- `E-Library`
- `Page`
- `Forum`
- Except `Repository`, `Partners` and `Groups` can modify their apps.
- Keep following in `local_settings.py` file:<br/>
`DEFAULT_GAPPS_LIST = [ u"E-Library", u"Page", u"Forum"]`
- `Events` is not part of the above list because, it's not fully ready. After it got to work, needs to be added.
> NROER: Gapp bar modified for 'Groups' and 'Partners'

- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
* Bug resolved in filtering the topic's resources based on educational levels. 
* Previously it was giving a list of values as a educational levels for each resource.
* For topic resources the educational levels are retrived as ``` {'resource_name': [list of educationallevels] } ```
* Modified ```get_contents()``` method  --> in ``` ndf_tags.py ```
* Now condition added in order to filter the resource when that selected educational level exists in list of levels for that topic resource.
* Currently filtering is tried only for educational levels in topic resources, will move towards the filtering based on all attributes of resources in next commit.
**What is to test**
* Go into any topic from curated zone, and test filtering based on educational level.
> Bug resolved in filtering the topic resources 

- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
* Condition fixed in str_to_dict()   -->  ndf_tags.py 
* info box condition fixed which used to convert str values to dict in order to display it on template.
* This change is made for updating the metastudio server, in temporary basis. Wil remove this condition if ths is not required.
> Small change fixed

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html
**Only in 'Home'(landing page) group-level GAPP bar made empty/clean:**
- To make `Home` as a landing page, group-level GAPP bar needs to be empty.
- After checking the site and group and other aspects, text - `Updates` and `GAPP's` will not be shown.
**Pending**
- To make static HTML page active as a landing page for the site.
> NROER: Only in 'Home'(landing page) group-level GAPP bar made empty/clean

- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_metastudio_settings.scss
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
- Link colors are made more darken.
- Visited links are shown with separate color.
**TEST**
- Possibly open `Updates` of group. Where more links appears. And do check for normal, hover, visited links.
- Also try with some other pages and list views.
> Hyperlink colors for visited, hover, normal links has been redefined

- gnowsys-ndf/gnowsys_ndf/ndf/management/commands/convert_mid_size_images.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/file.py
**Code for making 'mid_size_image' is modified to re-size image by preserving aspect ratio:**
- In the detail view of any image we are using/showing *mid_size_image*.
- When image gets uploaded, it gets converted to *mid_size_image* by `file.convert_mid_size_image()`.
- Previously this method used to convert image into fixed dimension of *500 X 300*.
- Which distorts the aspect ratio of almost all the images.
- And detail view of image shows distorted *mid_size_image*. So it's nothing to do with `CSS` properties -  `width` and or `height`.
- `convert_mid_size_image` method in `file.py` is now modified:
- Now this method compares *width* of uploaded image with `500` and accordingly takes action.
- So maximum allowed width is `500`. And in that proportion, height gets adjusted.
- If `width …
> Code for making 'mid_size_image' is modified to re-size image by preserving aspect ratio

- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
**Functionality implemented**
- In order to delete nodes from either Nodes or Triples collection, common function is written named as **delete_node()**
- This function makes use of two helper functions named as **delete_gattribute()** and **delete_grelation()**.
- However, these helper functions can also be used independently to delete GAttribute and GRelation node(s) respectively.
**What to test?**
1. Go into shell
2. Insert following import statement: ```from gnowsys_ndf.ndf.views.methods import *```
3. For description about these function(s), use either of the following statements (find examples):
(a) ```help(delete_node)```
(b) ```print delete_gattribute.__doc__```
4. Prepare a GSystem node which will have GAttribute node(s) and GRelation node(s) associated with it (this way you will …
> Function for deleting & purging node(s)

- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/collection_ajax_view.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/topics.py
**Breadcrumbs Navigation For Topic Pgae**
<hr/>
* As per the discussion for topic page breadcrumbs and its navigation, implemented entire navigation path of topic in theme map. 
* Previously there was no navigation for topic page. 
* Displaying "Related Topics" i.e siblings of topic on topic page left top panel as a list view
* Checks added for displaying related nodes only for topic page --> ```collection_ajax_view.html```
* Also implemented navigation of all related topic nodes with its breadcrumbs list. i.e When you click on related nodes , on details view page you can also see its navigation path where it belongs in entire theme map.
* Minor changes in ```style.css``` to remove the colour attribute on anchor tag in left panel.
* Now entire navigation can happen once you enter into the …
> Breadcrumbs navigation for topic page

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/UploadDoc.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_editor.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_forum.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_group.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_sub_group.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/document_edit.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/drawer_widget.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/edit_forum.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/edit_group.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/image_edit.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/forum.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/page.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/term.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/videoDashboard.py
Duplicate names(case-insensitive) check for following:
1. Group
2. Page
3. Forum
4. Term
5. Video (on edit)
- Added '@login_required' for creating/editing group
- Made user group name non-editable
- Checking of names(whether same name exists for same GST), is placed on submit button click and not on name textbox's change event. This is to prevent creating GSystems with empty name.
- Name check for Group under create_group.html code is modified. Existing mechanism was to fire an ajax call with the input group name followed by JS function to validate. This has been removed and re-written as: almost every view sends 'nodes_list' array to template(create/edit). On click of 'submit', check the input group name in the received array and take appropriate actions.
- 'node_edit_base.html' modified …
> Duplicate names(case-insensitive) check

- gnowsys-ndf/gnowsys_ndf/ndf/urls/__init__.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/file.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/home.py
- gnowsys-ndf/gnowsys_ndf/settings.py
**Default landing made to home-group, depending on variable value in `local_settings.py`:**
- Overwrite variable `GSTUDIO_SITE_LANDING_PAGE` in `local_settings.py` file.
- Default value is `udashboard` which will have following flow:
- Authenticated user: redirect to user dashboard
- Anonymous User  : redirect to home-group
- If value is `home`, which will have following flow:
- Authenticated / Anonymous User : redirect to home-group / site's landing page.
--
**Test:**
- Try with both the flows.
- In each attempt:
- Login and check for the landing page.
- As anonymous user give hit to domain name (local testing : `127.0.0.1:<port_no>`) and check for the  landing page
- To test add following in local_settings.py file: `GSTUDIO_SITE_LANDING_PAGE = "home"`
> Default landing made to home-group, depending on variable value in local_settings.py

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/group_dashboard.html
**Group-Profile picture upload functionality modified:**
- Present implementation was showing two buttons for uploading group profile pic.
- Now only one button `Edit` will appear.
1. On click of `Edit`, `Browse` will appear.
2. On selecting the file, it will check for it's mime type.
- If other than image type file selected, alert will prompt accordingly.
- If valid image selected, it will be displayed in the image area.
3. If image selected step completed successfully, two buttons - `Save` and `Cancel` will appear.
4. User can `Cancel` upload of selected image by clicking on `Cancel` button.
5. If everything is OK from user's perspective, Image will gets saved by clicking on `Save` button.
- UI is kept easy and minimal to simplify the process.
> Group-Profile picture upload functionality modified

- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_metastudio_styles.scss
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/group_dashboard.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/groupdashboard.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
**Toggle of text and link for "Update"/"About" on the app-bar:**
- Previously, `Updates` was prominent on second level app-bar. Now this has been changed to behave dynamically.
- Whenever `Updates` page is displayed, `About` text and link will appear on app-bar and vice-versa.
- Now on card listing of groups/partners, no text and app will appear on app-bar.
- CSS modified to show profile-pic (on top right) without distortion.
- CSS modified to show group-profile pic at center.
- Showing group-profile pic on group-details page.
-  `methods.get_group_name_id` modified to return group object, depending on parameters.
-  Example: `res_group_obj = get_group_name_id(group_name_or_id, True)`
- `res_group_obj` will contain entire object.
> Toggle of text and link for "Update"/"About" on the app-bar.

- gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/registration_form.html
- gnowsys-ndf/gnowsys_ndf/ndf/urls/__init__.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/email_registration.py
**Added *username* field in the user-registration form:**
- It is made as a compulsory field.
- Check has been put on it for it's uniqueness.
- This was necessary because, according to `django-email-registration`:
- If user with same username(characters before `@`) exists it was creating a long hash of the entered e-mail id as a username. And we are using username at multiple places.
- Even this was an issue reported.
- To achieve this, a subclass of `EmailRegistrationForm` has been added in `email_registration.py` file named: `class GstudioEmailRegistrationForm`.
- Now appropriate error messages will appear rather than one constant/fix error message.
--
**Test:**
- Create a new user. While creating user, do some errors.
e.g: While filling a form fill invalid email, password1 & password2 …
> Added username field in the user-registration form

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/group_dashboard.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/home.py
- gnowsys-ndf/gnowsys_ndf/settings.py
**Showing title of site according to site's name:**
- Currently, all the site's are showing `metaStudio` as title (text in tab).
- Which is made dynamic by adding `GSTUDIO_SITE_NAME=<site_name>` in `local_settings.py`.
- The use of template_tag `get_site_name_from_settings` is discarded. Instead using `get_site_variables` tag only.
- Because now function `get_site_variables` holds the value of `GSTUDIO_SITE_NAME`.
--
**Test:**
- Keep `GSTUDIO_SITE_NAME = "NROER"` or `GSTUDIO_SITE_NAME = <site_name>` in local_settings and test the title and other site specific features.
> Showing title of site according to site's name.

- gnowsys-ndf/gnowsys_ndf/ndf/views/task.py
for fetching task attributes the query was written to fetch it from the nodes collection which was a mistake as tasks attributes are stored in triples so replaces the queries to fetch from triples instead of nodes.
when we try to upload some file from the users group it was giving error due to wrong query to search a node with _type group , but in the case of author _type is author so the query has to be changed.
> queries corrected

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
**Minor changes**
* Previously when user sets the preferred language it was giving error, since it was not redirecting to existing context page. 
* Now temporarily the url redirection is resolved after setting preferred language. 
* But still there is a little work to do in that, whenever user changes the language from any context page , by accessing that preference language we should able to populate resources on a page. But currently its not happening. 
* Issue of url redirection is resolved which was arising previously, after setting language.
* Also tested the code for anonymous user as well as authenticated user for setting language
* Minor changes in ```get_preferred_language()  --> ndf_tags.py``` is:
* code added if user changes its preferred language after login. 
* Previously it …
> Bug resolved in url redirection after setting user preferred language 

- gnowsys-ndf/gnowsys_ndf/ndf/management/commands/filldb.py
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/drawer_widget.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/edit_group.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gapps_iconbar.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/videoDashboard.py
- gnowsys-ndf/gnowsys_ndf/settings.py
**NOTE:**
1. In order to update ```attribute_set``` field of **Group** and/or **Author** node, please follow below instructions:
a. Update ```gsystem_list``` in *filldb.py* with following values: **["Group", "Author"]**
b. Run following command: ```python manage.py filldb -nc```
2. If still ```attribute_set``` field is not getting populated with **apps_list** as one of the dictionary variable, then it means corresponding **GAttribute** node(s) are having ```status``` field value set as *None*; which needs to be replaced by **PUBLISHED**. To do so, perform following steps in your shell:
```python
apps_list_at = node_collection.find_one({"_type": "AttributeType", "name": "apps_list"})
apps_list_ga_cur = triple_collection.find({"_type": "GAttribute", "attribute_type.$id": apps_list_at._id, …
```
> Selection of GApps for groups & their listing in menu-bar updated

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/file.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/topics.py
**Breadcrumbs Enhancement**
* Minor css issue resolved on theme landing page
* When we click on breacrumbs for navigating through theme map, previously it was only redirecting to the 
selected node level, now it goes to selected node level and opens that node.
* Also after visiting any resource from topic's context, on clicking on "this resource teaches you" tab consisting topic node redirects it to topic page with proper breadcrumbs.
**How to test**
* go to topic page, and click on breadcrumbs , it will go to that particular node and opens its childrens
* also go to topic page, click on any resource, after redirecting to resource detail view , for navigating back to topic context , click on topic node inside "this topic teaches you" and it will redirect you to topic page with proper …
> Enhancement in breadcrumbs redirections

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/partner.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/partner_list.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/partner.py
**Showing list view of Partners and Groups with context-specific text:**
- Previously, The title, Header-text, Create-button url etc. was having prominent `Partners` despite of `Group` listing.
- Now this situation is handled and showing appropriate text everywhere on the list view.
> Showing list view of Partners and Groups with context-specific text

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/filters.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
**Filters to show altnames and reopened map widget:**
- Now filters will show `altnames` if it has value. Otherwise it will fall back to `name` field.
- Sending `altnames` from `ndf_tags` for the same.
- Showing map widget on detail view of node:
- If node has location then only *location widget* would be visible otherwise not.
> Filters to show altnames and reopened map widget

- gnowsys-ndf/gnowsys_ndf/factory_type.py
- gnowsys-ndf/gnowsys_ndf/ndf/management/commands/sync_existing_documents.py
- gnowsys-ndf/gnowsys_ndf/ndf/models.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
- gnowsys-ndf/gnowsys_ndf/settings.py
**Added script to update existing database entries as per new changes required by sub-groups:**
- Added following three new `GSystemType`'s:
1. `ProgramEventGroup`
2. `CourseEventroup`
3. `PartnerGroup`
- Changes in `Group` model:
- Added new field: `moderation_level: int`
- Removed `partner: bool`
- Updated `sync_existing_documents.py` which will do following:
- Remove `partner` field from `Group` instances.
- Add `moderation_level` field to `Group` instances.
- Adding creator of group instance in `group_admin` field if `group_admin` field is empty.
- Updated `settings.py` for following changes:
- Removed `Quize`, `Module` and `Batch` from `GSTUDIO_WORKING_GAPPS`.
- Added new variable `GSTUDIO_GROUP_MODERATION_LEVEL = 1`
- Other changes:
- Updated `get_group_name_id()` documentation to …
> Added script to update existing database entries as per new changes required by sub-groups

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/UploadDoc.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/file.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/home.py
**Videos to upload and play from domain only:**
- Commented video *upload* from `pandora api` part in `file.py`.
- Also commented video playing from `wetube` source in `node_ajax_view.html` template.
**Updated tag text area of file upload:**
- Previously, tag input area of file was taking comma separated tags. But it was without any checking and most of the times url's gets break.
- Now, same tag widget which is there in `node_edit_base.html` template is used.
- So it does check for tags with particular format and then only tags will gets appended/added. 
--
**TEST:**
- Upload a video and try to play that video.
- While uploading a this file, put some tags. Try to add tags with special characters except (-) hyphen.
--
**NOTE:**
- Video thumbnail generation part is commented. So no …
> Suspended uploading/playing videos to/from wetube

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/hierarchy_tree.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme_drag_zoom_d3tree.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/topics.py
**Made zoomable-collapsible-graph as default for themes-topic**
- Previously, Tree hierarchy `jQtree` graph was default.
- Now Collapsible graph, one which was zoom, drag capability is made default.
- Provided download button for downloading the graph.
- These graphs have unique urls now.
- Topic breadcrumb redirects back to tree hierarchy graph.
--
**NOTE:**
- Visit all the links related to graph.
> Made zoomable-collapsible-graph as default for themes-topic

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ebook.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/group.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/partner.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/partner_list.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/repository.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/theme.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/logout.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/course.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/e-book.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/e-library.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/file.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/partner.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/topics.py
**Showing GST's info from their instances**
- Showing name of `app`/`GSystemType` from their instance as `altnames`.
- If `altname` doesn't present fallback to `name` field.
- Displaying description of app from `content` field if it exists.
- This changes are applied for following apps/`GSystemTypes` (along with their DB `name`):
- `Repository` (no presence in DB)
- `Partners` (`PartnerGroup`)
- `Groups` (`Group`)
- `Curated Zone` (`Theme`)
- `eBook` (`E-Book`)
- `eCourses` (`Course`) 
- `eLibrary` (`E-Library`)
**Repository changes:**
- Showing repository metadata/info on LHS.
- Card layout changed to show only 3 in a row.
--
**TEST**
- Login as super user and got to admin/designer.
- change the `altnames` and `content_org` of these gst's.
- check for reflection of changes on respective …
> Showing GST's altname and content on LHS of page from their objects/DB

- gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
PE/CE groups will act as sub groups of the group from which they are created (using post_node and prior_node)
What to test:
1. Go to say,  'home' group.
2. Create a ProgramEvent.
In shell, check whether the newly created PE group's _id is saved in home group's post_node and also whether the home group's _id is saved in PE group's prior_node
> Minor Update on Program/Course Event Group

- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
The cause was get_drawers method was executing for loop two times.
One is the old for loop, other is the list comprehension for loop(recently added at many places for optimization). Hence, commented old for loop. 
This bug populated same results twice in the drawer.
> Minor bug in drawers resolved

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_group.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_selector.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
**New generic selector widget added:**
- It's compact, searchable, multi-selector.
- Created new template `widget_selector.html`.
- Provided core functions as well as utility functions to interact with selection.
- Written in pure JS to optimize the performance.
- Selection item's order can be changed with click on selected items.
**Implemented widget for gapp selection:**
- Currently implemented/included this widget in `create_group` template.
- Added new template tag `get_group_gapps` to return group level apps as a list of mongodb query objects.
- Apps selection enabled for group editing as well as new group creation.
**Future /Expected features in the widget:**
- Make it AJAX enabled to load the selections.
- Providing option to choose the key for selection and search.
--
**TEST**
- …
> New generic selector widget added. Implemented for gapp selection. 

- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_metastudio_settings.scss
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/breadcrumb.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/group.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/hierarchy_tree.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_details_base.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_selector.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
- gnowsys-ndf/gnowsys_ndf/ndf/urls/file.py
- gnowsys-ndf/gnowsys_ndf/ndf/urls/topics.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/file.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/topics.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/videoDashboard.py
**Implemented Breadcrumb:**
- Initial phase of breadcrumb has been implemented.
- Initially provided *three* levels of breadcrumbs.
- Showing wherever it's required.
- Kept in base.html and defined one `ndf_tag` for the same.
- Maintaining one exception list in `ndf_tag` to exclude it in non desired locations.
- Updated CSS and SCSS of breadcrumb.
--
**Other Subtle Changes:**
- While coming back to theme hierarchy tree from topic, none of the element was clickable. This is resolved.
- On click to resources under topics, detail view of resource is shown in overlay.
- Separated node content from `node_ajax_view.html` to newer template.
- Added new method `get_prior_node_hierarchy` in `method.py`. This method will return all the prior node's hierarchy list.
> Breadcrumb Implemented. Also some minor issues addressed.

- gnowsys-ndf/gnowsys_ndf/ndf/views/file.py
At some places, for saving files we use 'save_file' view.
In case of simple upload, we pass empty values for fields like content and tags.
There was no check for tags value received and also we loop over it to save it with the tags field of the node which raise the following common error: TypeError: 'NoneType' object is not iterable
> File saving error fixed

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ebook.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file_list_tab.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/filters.html
- gnowsys-ndf/gnowsys_ndf/ndf/urls/e-book.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/e-book.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/e-library.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
- gnowsys-ndf/gnowsys_ndf/settings.py
**Added url based filters in eBooks:**
- Now filters widget has been put in `eBooks` section.
- This filter has been implemented url based.
- So that if new filter has been added, url gets updated.
- Now this selected filter url can be shared.
- The filter result is paginated.
--
**Other Changes:**
- Changed DB name back to `studio-dev`.
- Created new method in method.py to convert filter data into mongodb consumable query dict.
- Added new utility JS functions in `filters.html` for url based filter implementation.
> Added url based filters in eBooks

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/invite_admins.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/invite_users.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
The drawers populating the users in 'Subscribe Users/Admins', earlier displayed only email-ids.
In this commit, it is modified to display both username and email.
Please test, search feature also in the above said user drawers.
> User subscription updates

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/partner_showcase.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/repository.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/simple_card.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
- gnowsys-ndf/gnowsys_ndf/ndf/urls/partner.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/e-library.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/partner.py
- gnowsys-ndf/gnowsys_ndf/settings.py
**Implemented Partner Showcase:**
- Made **Partner Showcase** functional in repository.
- On click of *Partner Showcase* section from repository:
- Intermediate card listing will appear consists of text contained in `source` attribute and which is `partner` as well.
- Using the same `simple_card.html` template to show cards.
- On click of these cards, user is getting redirected to filtered `e-library` (of `home` group) based on selected `source` or `partber`.
- defined new url and view in corr partner url and view respectively.
--
- Now filters can have dynamic values to get populated in second level selector.
- Added new filter `source` which holds possible values from resources in DB.
- Updated `GSTUDIO_FILTERS` in `settings.py` to have `source` for `e-library` and …
> Implemented Partner Showcase and some other changes

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/action_panel.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
1. For Cross publish, instead of the drawer_widget, now a listing of all groups with a checkbox and group-name will appear.
2. The group's that are already held in node's group-set, are checked by default.
3. If 'home' is in node's group-set, it is checked by default and is disabled; as a user is not allowed to remove resource from 'home' group
> Cross-Publish feature redefined

- gnowsys-ndf/gnowsys_ndf/ndf/management/commands/sync_existing_documents.py
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file_list_tab.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/footer.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/landing_page_nroer.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/partner_showcase.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/partner.py
1. Display messages when using filters which return no results. "Sorry, No such file is found."
2. 'Issue' in footer changed to 'Report an Issue' that will redirect to new-issue form on gitlab(if logged-in in gitlab) in new tab
3. Provided a link to the old site(nroer.in) in landing page of NROER
4. Partner cards in Partner Showcase to have the profile-pic uploaded in that respective partner group.
5. Listing of partners in partner-showcase in alphabetic order
> Updates in Partner showcase, footer and landing page of OER

- gnowsys-ndf/gnowsys_ndf/ndf/management/commands/filldb.py
- gnowsys-ndf/gnowsys_ndf/ndf/management/commands/sync_existing_documents.py
- gnowsys-ndf/gnowsys_ndf/ndf/signals.py
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_details_base.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/topic_details.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/registration/activation_email.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/moderation.py
**desk group functionality implemented:**
- Added code in `filldb` to have `desk` group as factory group along with home group.
- Currently, this group is with `edit_policy` as `EDITABLE_NON_MODERATED`, which later on can be change to moderated group with different level of moderation.
- Updating `author_set` of desk group to have same set of user's as that of `home` group.
--
**Enabled creation of underlying sub-groups as mod-groups**
- Previously, creation of moderation group as sub-group was not possible, which is enabled now.
- Some intermediate functions modified to have mod group as sub-group.
- Query modified to select mod and normal sub-group/s. 
- Redundant function 'get_top_group_of_hierarchy' in `moderation.py` commented and using same function from `group.py`.
- If no-subgroup …
> Desk group functionality implemented. Enabled creation and listing of mod group as sub-group.

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/moderation.py
**Enabled cross publishing in moderated groups too:**
- Prev. cross publish to normal group was possible, now cross-publish to moderated group is made feasible.
- When resource cross published it gets into 1st intermediate underlying sub-mod-group.
- When resource is in any of the underlying mod-group, then checkbox of top-mod group is checked and made disabled in cross publish group selector widget.
- updated moderation_status() to return only result/response dict.
- Now we could get extra-key value from `set_drawer_widget` by supplying additional key argument.
> Enabled cross publishing in moderated groups too

- gnowsys-ndf/gnowsys_ndf/ndf/templates/error_base.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/action_panel.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/graph_collection.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/graph_concept.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/graph_dependency.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/topic_details.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/topic_resources_listing.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/page.py
**Graph made open for Page:**
- Previously graph was visible only for `topics`.
- Now it has made open even for `pages`.
- Only two (dependency and collection) graphs made available and concept graph commented.
- If any of the graph is applicable to that node's detail view then only that particular graph will be visible.
- Made JS dependencies of graph to load without async.
--
**No two pages can have same name in same group**
- Check has been imposed for not to have two pages with same name in the same group.
- Now this check is put on back-end view. So that no new page with same name gets created accidentally too.
- Even check is added for after edit of page-name to one matching with already existing page in the same group.
- First time error template is used to show the error. Keeping …
> Graph made open for Page. No two pages can have same name in same group.

- gnowsys-ndf/gnowsys_ndf/ndf/management/commands/nroer_data_entry.py
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/file.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
**Modified nroer_data_entry script to take correct value for field language:**
- Previously, the tuple value for language was taken as string. So by default comparison condition fails and fall back value of `('en', 'English')` used to get assigned to resource.
- With the current changes, proper casting of string value happens to tuple and appropriate values ges to resource.
- Also script extended to update existing documents with appropriate tuple value.
--
- RCS version checking is done with condition. So that no error should happen in the case of any file mismatch/misplace.
- `get_language_tuple()` updated to check for tuple and/or list value of language.
--
**Note:**
- Try to re-run/fresh-run of the CSV (esp with hindi/other-lang resources) with new …
> Modified nroer_data_entry script to take correct value for field language.

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/action_panel.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/groupdashboard.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_details_base.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
* Replaced 'List members' option with 'List Programs' (for Listing of ProgramEvents Issue ref.[#49](https://gitlab.com/gnowledge/gstudio/issues/49))
* Commented related js and ajax calls.
* Commented 'Info-box' code which was taking enormous amount of time to process
What to test:
Take the pull and check if group dashboard takes lesser time to load as compared to earlier. 
Check with groups having large number of users
> Group Landing page performance issue fixed

- gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
On uploading new profile pic or using from existing profile-pics, the group-set of file-object will be set to warehouse.
What to test:
Upload profile pic before this pull, and check in the current group's file listing.
Take this pull, upload a new profile pic again and this time it should go to warehouse group ONLY.
Also, use old/existing profile pics, this should also go into the warehouse
> Move profile pics to warehouse

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/action_panel.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_units.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/course.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/page.py
Saving a page from course-units context, earlier was not setting the 'type_of' field. Hence, loading editor which is based on type_of was becoming ambigous (As the node exists and type_of is empty).
Now, list of options is provided while creating page in course units too.
Saving 'type_of' [Wiki, Blog, Info] is now handled in get_node_common_fields method.
> Setting page type field 

- gnowsys-ndf/gnowsys_ndf/ndf/models.py
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/action_panel.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/quiz_player.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
- gnowsys-ndf/gnowsys_ndf/ndf/urls/ajax-urls.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
* New field added in action-panel (RHS): 'Views'
* Views 
- By default, shows a link 'Click to see No of Views'
- Ajax call to fetch count of views
- Replaces the earlier link message with views in 'My views/ Total Views' pattern.
- In case of AnonymousUser, displays 'Total Views'
- Removes hyperlink from count msg to prevent consecutive ajax calls 
* New ajax-view:
- 'get_views_count': 
- Queries on benchmark collection for total-views.
- User views fetched from total-views using 'where' clause. Hence, preventing another query on dB
> Analytics: Display view counts of particular resource

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/simple_card.html
previously SVG and GIF images were not rendering properly on card thumbnails, this is fixed in simple_card.html.
> svg,gif  thumbnail not showing on card issue 

- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/js/ckPlugins/addImage/plugin.js
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/js/ckeditor-config.js
* Tab spacing is enabled in CKEditor. default spacing is 4
* Uploaded image's URL was saved with origin,now it is removed.
* basic entities such as ' ' and " " were disabled by default, i have enabled it with 
**config.entities=false**
> bug/issue fixes in CKEditor

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/topic_resources_listing.html
**Topic detail: showing only text of image and video instead of thumbnails:**
- Previously, we used to show thumbnails for image resources.
- Now only text will appear.
> Topic detail: showing only text of image and video instead of thumbnails

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_group.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_selector.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
**Updated selector-widget:**
- Previously, we could use/include only one selector-widget as it was html `id` based.
- Now everything has converted to class based and hence modified JS accordingly.
- Also added doc-strings/information about how to use this widget.
--
**TEST**
- Try to use this widget for setting `GAPPs`. Cross check whether it's happening or not.
--
**Main modified files**
- `widget_selector.html`
> Updated selector-widget and it's JS

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_analytics.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_units.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_event_group.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gcourse_units.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ggallerymodal.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/unit_player.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/file.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/imageDashboard.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/page.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/videoDashboard.py
Updates:
1. Announcing course from announced course. Link help pages and interaction settings.
2. Displaying resources list in unit authoring bug fixed
3. Show rating in analytics data view if and only if o/p is greater than zero. Increase height of rating image
4. Fetch info pages of using group_set in assigning help link
5. Display an alert with user confirmation required message when announcing form is submitted
6. Separated cloning function from replicate_resource to create_clone. Help pages will be linked after announcement. New Help page nodes are created accordingly
7. Use widget_selector.html for selecting info pages in node_edit_base
8. New ndf_tag 'get_help_pages_of_node' defined
9. Fetch node's info page using ndf_tag in unit-player
10. Fetch and perform json.loads of all …
> Announcing course from announced course

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_analytics.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gcourse_event_group.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ggallerymodal.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/ggallerypage.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_edit_base.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/note_page.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/scrolldata.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/analytics_methods.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/file.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/imageDashboard.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/page.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/videoDashboard.py
- gnowsys-ndf/gnowsys_ndf/settings.py
Note: Override `GSTUDIO_ENABLE_USER_DASHBOARD = False` in local_settings.py
This will make RHS userdashboard link not clickable.
Updates:
1. Configurable user dashboard enabling RHS corner
2. Score points made configurable by adding variables in settings.py
3. Commented next session display in course-player
4. Show 'uploaded' instead of 'created' in notifications if resource is file
5. Pluralize values in course about
6. Show comments in notifications
7. Display tags with hyperlink in notebook detail and file detail
8. Tags in gallerymodal working
9. Redirect to resource/file detail view after edit save
10. Set font-size in tabs in file detail view of course player
11. Selected file is shown when uploading to gallery. If its image, display a thumbnail size image or else display the name
> Bug fixes in Course-player

- doc/deployer/set_course_structure_group_set.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/analytics_methods.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
Note: Run `execfile('../doc/deployer/set_group_set.py')`
- In the earlier commits, the course tree displayed Complete(Check mark), Incomplete(Warning mark), based on whether the user has commented on the nested resources of respective Sections, Subsections and Units.
- This logic has been changed. 
- Now, to calculate the Completion and In-completion status, we will be checking whether the user has seen/visited the nested resources of respective Sections, Subsections and Units.
- Hence, the latest implementation, in this PR, fetches the status data from **benchmark** collection.
New Script:
`set_course_structure_group_set.py`
- The nested structure of a CourseEvent did not held any data in group_set field, This script is used to update the group_set field of existing CourseEvent nested …
> Logic changed for calculating Completion/Incompletion status in Course tree

- gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
Earlier, base course files which were on GridFS, were copied with same attributes and new File instance.
This logic has been changed to adapt Filehive implementation.
Now, while announcing course, the base course resources are cloned using **copy()** method.
Only fields updated for new instance are:  
- _id
- group_set
- status
- modified_by
- created_by
- prior_node
- contributors
Along with that, if course is announced from announced course, raw-material file's group-set is updated with new course-group's _id. (Cross-publishing the files)
> Announcing logic redesigned.

- doc/deployer/delete_courseevent.py
Go to shell : `python manage.py shell`
Run : `execfile('../doc/deployer/delete_courseevent.py')`
It will display total number of course events(groups) that exists and ask confirmation(y/Y) for every group.
On confirming with 'y' or 'Y', it will display total number of resources of that group that are to be deleted.
> CourseEvent Deletion script added

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/simple_card.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
* e-Pub file not rendering in file-hive issue fixed.
* Org content of card's content area was not showing properly as we  were showing HTML content.
so  we are using `striptags` in order to show content without any markup
> e-Pubs not rendering error

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/simple_card.html
* checkbox will not appear if group policy is `NON_EDITABLE`
> checkbox visibility policy for simple cards

- gnowsys-ndf/gnowsys_ndf/ndf/models.py
**If Add-Buddy feature is enabled, adding buddies user id in contributors field of Node instance**:
- Get all user id's of active buddies with currently logged in user.
- Check if each of buddy-user-id does not exists in contributors of node object, add it.
- Added code in `models.Node.save()`
--
**Added new method: `can_access()` in `class Group`**:
- Returns `True` if user can access (read/edit/write) group resource.
- ARGS:
1. `user_id` (int): Django User id
2. `group` (Group or ObjectID or str-of-group-name): It can be either group's                                                         *object* or *_id* or *name*.
Added/Copied `get_group_name_id()` under `models.Group` class.
--
**To Test**
Check the `contributors` field value after doing following actions:
- Create a page without …
> Adding buddies user id in contributors field of Node instance. Added some useful methods under models.Group.

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_group.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/edit_group.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
**mongokit branch**
Updates: 
- Group edit page will have page-edit view, i.e we can edit/add collection, metadata.
What to test:
Go to a group dashboard. Click on edit. You would find a btn 'More edit options', this will redirect to old group-edit view. Add some resources in collection, set GAPPs and save.
> Group-edit functionality restored.

- gnowsys-ndf/gnowsys_ndf/ndf/models.py
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/buddy.py
**Added methods to retrieve, remove, list sitewide buddies:**
- Added following new *`@staticmethods`*:
- `sitewide_all_buddies()`
- `sitewide_all_active_buddies()`
- `sitewide_remove_all_buddies()`
--
**Fixed issue of saving removed buddies in contributors:**
- Previously, even after removing buddies, their `id` used to get added in `contributors` field. This bug is fixed.
**TEST:**
- Create new page with some buddies. Check for contributors of newly created page. It should contain current buddies id's.
- Now remove/alter buddies and try to create/modify page. It should only show user `id`'s of current buddies and not of all buddy `id`'s in contributor's of newly-created/modified page.
> Buddy: Added methods to retrieve, remove, list sitewide buddies. Fixed issue of saving removed buddies in contributors.

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/action_panel.html
W.r.t [Issue](https://gitlab.com/gnowledge/gstudio/issues/276).
Font-size is increased and also buttons height should be balanced with button besides to it.
Hence, swapped btns Cross-publish and Delete.
Now, History and Delete will be on one row and Cross-publish will be on another row.
> Increase action buttons font size

- gnowsys-ndf/gnowsys_ndf/ndf/management/commands/fillCounter.py
- gnowsys-ndf/gnowsys_ndf/ndf/models.py
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/action_panel.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gcollection_ajax_view.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/buddy.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/discussion.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/page.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/ratings.py
**Implemented Counter analytics with buddies and contributors:**
- Previously analytics gets mapped to *logged-in-user-id* and *created-by*.
- Now Counter-Analytics will consider:
- All the user's in `contributors` instead of single `created_by` user.
- All active buddies with logged-in user's.
- *Ratings:*
- All buddies will be added in `Node.ratings` dict.
- Considering ratings for all buddies counter instance as well as all contributors of page/note/file resource.
- *Comments:*
- All the buddies as well as `contributors` counter instances will get updated on comment-on-others or gain-of-comment on resource.
- *Visit:*
- Updating contributors and buddies counter instances on page/note and file visit.
- *Create:*
- Updating buddy user's counter instance on note-creation/file-upload with …
> Implemented Counter analytics with buddies and contributors

- gnowsys-ndf/gnowsys_ndf/ndf/models.py
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/base.html
**Models: some issue related low performing Node.save() fixed:**
- Previously, we were calculating rcs file's current version when each time `Node.save()` is being called. Which spposed to be called only when `group_id` argument is passed in `save()` to persist version no in `snapshot` field.
- Now this issue has been fixed and only on group level documents `.save()` this method will gets called. 
- Another issue with getting current version of rcs file is:
- As on when object gets updated, it's rcs file gets updated and accordingly it's version.
- Some of the factory object's RCS like `has_profile_pic` are getting updated regularly (this is because it is embedded in another document/grelation object, so when top/parent object gets updated, embedded doc also get updated).
- As version no …
> Models: some issue related low performing Node.save() fixed

- gnowsys-ndf/gnowsys_ndf/ndf/rcslib.py
Some print statements that appeared for write operations that eventually updated RCS:
```
/data/rcs-repo/Nodes/3/a/0/5752ad8b2e01310f17fd0ba3.json,v  <--  /data/rcs-repo/Nodes/3/a/0/5752ad8b2e01310f17fd0ba3.json
new revision: 1.42; previous revision: 1.41
done
/data/rcs-repo/Nodes/5/a/0/5752ad8b2e01310f17fd0ba5.json,v  -->  /data/rcs-repo/Nodes/5/a/0/5752ad8b2e01310f17fd0ba5.json
revision 1.41 (locked)
done
```
have been removed using **-q** option.
Links for reference: [ci](https://linux.die.net/man/1/ci), [co](http://linuxcommand.org/man_pages/co1.html)
> Blocked RCS print statements.

- gnowsys-ndf/fabfile.py
- gnowsys-ndf/gnowsys_ndf/ndf/management/commands/purge_group.py
- gnowsys-ndf/gnowsys_ndf/ndf/models.py
- requirements.txt
**Added group purge functionality**
- Added new method named `purge_group` under `models.Group`.
- Method can be used in views as well as from terminal (django base commands, fab command etc.)
- Takes input either groups name or _id
- Throws an exception if group not found.
- Shows stats of resources(2 types) under group:
1. Shared Resources: Resources falling under many groups.
2. Only/Unique Resources: Resources falling under only this group.
- After taking confirmation from user:
- purges unique resources.
- purges group itself.
- removes _id of group-to-be-purge from `group_set` of shared resources.
- Also added corresponding `fab` command for the same.
--
**Test:** Use any of following comand
- `python manage.py purge_group`
- `fab purge_group`
> Added group purge functionality

- gnowsys-ndf/gnowsys_ndf/ndf/management/commands/create_index.py
- gnowsys-ndf/gnowsys_ndf/ndf/models.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/forum.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/utils.py
**Fixed issue of not updating attribute_set values and thread creation:**
- Previously, while updating GAttribute, node's/GSystem's attribute_set was not getting updated.
- Replaced, mongo *update* query to list of dict `[{}, {}, ..]` with small private python method.
- Also replaced update query with `.save` so that it's RCS will get updated.
- After updating code for triples, thread creation was giving error, resolved in `methods.create_grelation()`.
> Fixed issue of not updating attribute_set values and thread creation.

- doc/deployer/copy_move_group_files.py
- doc/deployer/migrate_group_resources.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
Ref Issue #1589 
1. Two Levels of clone operations added:
- Clone: Replicates a node and NOT its corresponding Triples.
- Hard Clone: Replicates a node ALSO  its corresponding Triples.
2. request arg made non-mandatory for method replicate_resource
3. Rename copy/move/clone script.
> 'Clone' option in deployer script copy_move_group_files.py

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_group.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/create_partner.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/file.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/groupdashboard.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_content.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/node_ajax_view.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/partner_list.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/partner_showcase.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/upload_pic_widget.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
- gnowsys-ndf/gnowsys_ndf/ndf/urls/trash.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/trash.py
- gnowsys-ndf/gnowsys_ndf/settings.py
- Social share button enabled with fb and twitter buttons.
- Create/Edit individual partner not getting saved issue fixed.
- Orgitdown editor in partners page replaced with CKEditor.
- Added configurable  variable `GSTUDIO_TWITTER_VIA` to tag default twitter id and `GSTUDIO_FACEBOOK_APP_ID` added for facebook app id.
- For example : override following variables in local_settings.py  GSTUDIO_TWITTER_VIA = "atMetaStudio"
GSTUDIO_FACEBOOK_APP_ID = "123456789".
> Social share button enabled and fixed issues with partners(NROER)

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/unit_structure.html
- gnowsys-ndf/gnowsys_ndf/ndf/urls/ajax-urls.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
**Activity Player: removing activity from lesson done**
- Added JS call to remove activity from lesson.
- Added url and view to remove activity's id from parent's `collection_set`.
---
**Added generic method `remove_from_nodelist` to remove `ObjectId` from list**
- This takes following 3 args:
- `parent_node_id`
- `child_node_id`
- node field name
- This method can be used for all `Node` instances field having list of `ObjectId`.
---
**Test**:
- Remove activity from lesson from activity player
> Activity Player: removing activity from lesson done. Added generic method to remove ObjectId from Node's list

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/unit_structure.html
- gnowsys-ndf/gnowsys_ndf/ndf/urls/ajax-urls.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
**Added functionality to delete lesson:**
- Added JS function to deleteNode.
- `deleteNode(node_to_delete, $el_to_remove, deletion_type=0)`
- Added *generic* ajax url and method `ajax_delete_node` which is calling `methods.delete_node()`
- `ajax_delete_node` can be used at many places wherever we need to delete/purge node.
---
**Test:**
- Delete existing/newly-created lesson.
> Added functionality to delete lesson.

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gevent_base.html
- gnowsys-ndf/gnowsys_ndf/ndf/urls/trash.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/explore.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/trash.py
**Unit delete functionality:**
- Added UI for delete unit in detail view.
- It's using reveal modal. Confirms and then proceeds for delete unit group.
- Added url for delete_resource with redirect url and handled same in view.
- Depending on provided `url_name` redirection will happen after group/unit deletion.
- Also preserved old url for group delete. To avoid code break in existing code.
- After unit deletion, redirection will happen to unit's listing.
- Modified query for getting all the units which are published.
- After unit deletion it will get listed in `Trash` group's data-review.
- Unit Restoration will happen on click of `Restore` button.
*NOTE: It's a **Delete** feature and not **Purge***
---
**Test:**
- **DELETE Feature**
- Get into detail view of any unit.
- `Delete` option …
> Unit delete functionality added

- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/clix-activity-styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/opensans-fonts.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/epub/epub_activity_skeleton.xhtml
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/epub/epub_static_dependencies.json
- OpenSans Fonts path has been overridden to the corrected path.
- The change has been reflected to clix_activity_styles, fonts.css, epub inherited files.
> Fonts: Reflected to OpenSans

- gnowsys-ndf/gnowsys_ndf/ndf/middleware/SetCookie.py
- gnowsys-ndf/gnowsys_ndf/settings.py
**Added session middleware to set cookie 'user_id' required for Assessment/oac**
- For every request, `user_id` cookie will be set.
---
**TEST**
- After taking pull, check `user_id` cookie for different type's of user (including anonymous user) in browser's developer tool.
- For chrome: `Application` > `Cookies` > `<domain-name>` and check for key value in right pane.
- For Firefox: `Cookies` tab.
> Added session middleware to set cookie 'user_id' required for Assessment/oac

- doc/deployer/del_has_thread_update.py
For threads not having `release_response` attr, set default to True.
Run `execfile('../doc/deployer/del_has_thread_update.py')` in shell.
> Update on Interactions

- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_enroll.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/simple_filters.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/buddy.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
Since, for every buddy `Enroll` action has to be explicit, the `Enroll` option in `Course|Unit`, has provision to enroll each and every buddy from a single UI.
The `Enroll` button, now will open an overlay listing all the `buddies (usernames)`, corresponding to the enrollment status. A check box is provided to enroll the buddy (one at a time).
Also, an option of `Enroll All Users` is provided, which enrolls all the buddies in a single click.
New Update:
Include logged-in user in enroll listing in overlay
> Enroll for Buddies

- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/metastudio/styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/nroer/styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/tiss/styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_app_styles.scss
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gin-line-texteditor.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header_clix.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/in-line-texteditor.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/quiz_player.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/group.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
- gnowsys-ndf/gnowsys_ndf/settings.py
New configurable variable added:
1.  `DEFAULT_DISCUSSION_LABEL = Feedback` 
2.  `GSTUDIO_SITE_SECONDARY_LOGO`
- This `DEFAULT_DISCUSSION_LABEL` value will be used to create Thread objects `interaction_type` as default. [E.g Notebook of Course.]
- Includes other CSS Updates for Discussion template
- `Question/Quiz-item` content will not display HTML tags in quiz-player.
- site logos configurable
`Comments/Replies` total count will be visible on Discussion button if `release_response` is set to `True`.
Also, the ajax call to alert the user about new comments posted is also made if if `release_response` is set to `True`
> Updates on Discussion module

- gnowsys-ndf/gnowsys_ndf/ndf/management/commands/group_export.py
- gnowsys-ndf/gnowsys_ndf/ndf/management/commands/group_import.py
Follow the same commands that are used for dump-restore:
```
python manage.py group_export
python manage.py group_import
```
When asks for the node `ObjectId` whose is to be taken, we can add `Module's ObjectId`.
Dump & Restoration will act on the  Groups that are part of the Module's `collection_set`, out of which the user can choose the units to be dumped.
_More Description will be added soon_
> Module level dump-restore.

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_interaction.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/ajax_views.py
- requirements.txt
For cases where, interactions are set to activity pages after announcing, the interactions will be applied.
For draft units, when interactions are applied, the attribute that will be set is `player_discussion_enable`, which on announce converts into `discussion_enable`.
For announced units, the attribute for interactions will be `discussion_enable`.
Update:
- Moved cryptography to bottom of requirements.txt file
> Apply discussion-enable in interactions-widget on pages irrespective of group-type(draft/announced)

- gnowsys-ndf/gnowsys_ndf/ndf/views/explore.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/module.py
For SuperUsers, in `Explore Drafts`, display all units(`Draft` and `Announced`). Applied same logic for `Module` detail view.
For regular users, Announced Unit will be displayed in `Module` and `Explore` tab.
Drafts units will be displayed iff, the user is either a member, admin or creator of the draft unit.
> Access privileges updated

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/in-line-texteditor.html
- Reply without enrollment bug fixed.
- Comment/discussion viewing not required login in assets.
> Reply without enrollment bug

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header_clix.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
- gnowsys-ndf/gnowsys_ndf/settings.py
Bug: The modifications made in existing `LANGUAGES` settings variable affected the node's language field that stored as following:
```
node.language = ('hi', u'\u0939\u093f\u0902\u0926\u0940')
```
overriding/instead of following:
```
node.language = ('hi', u'Hindi')
```
This change was made to display languages in native text for easy readability. However, this change hampered listing of Courses based on the `GSTUDIO_PRIMARY_COURSE_LANGUAGE`
Solution:
1. Reset `LANGUAGES` settings variable
2. New settings variable `HEADER_LANGUAGES` defined to hold language tuples intended to be displayed in site-header language options
> Update on Language values

- gnowsys-ndf/gnowsys_ndf/ndf/management/commands/group_import.py
- gnowsys-ndf/gnowsys_ndf/ndf/models.py
Following is the detailed explanation of bugs encountered on exporting/importing Groups:
[A]. **Filehives:** (in export)
1. Prior to copying a node's `RCS` to dump, the `RCS` is built for it, to ensure the updated version is packed. But an issue was raised with `Filehives` nodes. 
2. If a `Filehive` object exists in `mongodB` and its corresponding `RCS` file does not exist, the `save()` method of `models.py` should generate the `RCS` file, as it does for rest all types of `Nodes`. 
3. Due to an attribute error, this was skipped making it unable to generate `RCS` file, and eventually the export of  this node is skipped.
__Solution__:
The attribute error is fixed.
[B]. **RCS checkout:** (in import)
1. The import script parses through each `RCS` file from the `RCS` directory of the dump, …
> Bugs fixed: Filehives save() method for an existing node and fetching json file from rcs

- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/course_pages.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/unit_structure.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
1. Edit metadata in settings wheel shifted at the bottom above delete.
2. CMS lesson structure given a width of small-10 columns.
3. The actionable move up, move down, edit and delete have default display, on hover they have been highlighted with different color.
4. Edit pencil given same background as the CMS tab color.
> CMS Lesson authoring Fixes

- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/epub/tool_mapping.json
- gnowsys-ndf/gnowsys_ndf/ndf/views/export_to_epub.py
For media of mime type as `aaplication/*` that is part of page content, should be part of exported epub.
> bug fixed in exporting content into epub 

- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/card_group.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gbase.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_dashboard.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_explore.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/module_detail.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_enroll.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_photo_upload.html
New layout for unit-card with three horizontal divisions:
a. Banner
b. Name/Altnames
c. Footer with Metadata:
- Number of Lessons/Sections
- Number of enrolled/joined students/members
Use cases to be tested:
1. As Anonymous and Admin users
- Check for card layout when no actions in card footer
2. As student/regular user
- Check for card layout when actions such as `Enroll, Enrolled and Enroll <buddy>` in card footer
3. `My desk -> My Courses`
- Check for card layout when no actions in card footer
4. `My desk -> My Performance`
- Check for card layout when actions such as `View` in card footer
Other updates:
`Enrolled` on card on hover styling modified.
For a quick glimpse:
> Redesigned Unit-card layout

- gnowsys-ndf/gnowsys_ndf/ndf/management/commands/activity_timespent.py
- gnowsys-ndf/gnowsys_ndf/ndf/management/commands/sync_existing_documents.py
- gnowsys-ndf/gnowsys_ndf/ndf/models/benchmark.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/explore.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/tasks.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/tools.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/userDashboard.py
Run `python manage.py sync_existing_documents`
Run `python manage.py activity_timespent <group_id_or_name> <username>`
Console gives all details of total visits and calculated results for each visit.
User and group-wide `csv` to be created in `/data/gstudio-exported-users-analytics-csvs/`
Columns in csv: `VisitedOn|Lesson|Activity|Timespent`
> Provision to calculate Time spent(in seconds) by user on activity-detail 

- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/assets.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gbase.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms_dashboard.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_enroll.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/explore.py
- gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
- "As is: My Workspaces To be: My Courses"
- On Module card after enrollment it displays Joined.
- The Enrollment overlay shows Join instead of Enroll
- While creating Asset either remove Choose Topic or keep CLIx as default instead of NROER
- Two Topic Map tabs instead of one
- Rating doesnt work at most of the places in Activity Page
> 18.04 release issues after testing.

- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/module_detail.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/widget_photo_upload.html
- gnowsys-ndf/gnowsys_ndf/ndf/views/module.py
Redesigned module detail template to display description, units under modules and other metadata information efficiently.
Followed foll. design layout:
Design impl:
> Module detail redesigned

- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/clix-activity-styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/videojs-skin-color.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/add_asset.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/lms.html
* Defined a single point to change the theme-color of the platform.
* All HTML components whose styling was defined separately, shall now invoke from global variable `PRIMARY-THEME-COLOR`.
What to Test:
1. In `clix2018.scss`, modify the `$primary-theme-color` value and check for reflection in all Course/Module/Unit/Activity-player pages for the changed theme-color
2. In `clix-activity-styles.css`, modify `--primary-theme` in `root` dict, to view color change in all activity pages in player (headers, blockqoutes, etc)
3. In `videojs-skin-color.css`, modify `--primary-theme` in `root` dict to check controls of video-plaer widget color change
> Theme based Styling for entire platform.

- gnowsys-ndf/gnowsys_ndf/ndf/middleware/UserRestrictMiddleware.py
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/user_course_analytics.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
- gnowsys-ndf/gnowsys_ndf/settings.py
Updates:
1. Middleware to prevent login page for logged-in users
2. Display user's profile-name in preogress-report
> Middleware to prevent login page for logged-in users and other update

- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/clix-activity-styles.css
**Bug Reported:** 
In chrome audio overlaps on text in word help activity (Specific to some versions).
In chrome all options in audio (eg:mute, download) are not visible in word help activity (Specific to some versions).
**Solution:** 
Eliminate issue by removing width property in css for audio.
> Chrome audio overlap issue

- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix_styles.scss
**Bug Reported:**  
Descriptive multi-line statements in e-notes as well as notebook not displayed properly.  
**Bug Fixed:**  
Modified the _clix2017.scss and _clix_styles.scss and attached a word-wrap property to the note-text class.
---
**Steps to fix the above Bug**
+ Navigated to the note-text property of the _clix2017.scss and _clix_styles.scss and attached a word-wrap property for the same.
+ After modification of the above two files, compiled the following sass files at manage.py level by using following command:
`compass watch`
> Modified _clix2017.scss and _clix_styles.scss. Attached word-wrap property to note-text class

- gnowsys-ndf/gnowsys_ndf/ndf/views/gcourse.py
**Changes related to i2c progress csv creation**
---
- Issue : Progress CSV not getting generated for i2c courses
- Fix     : Have changed the function (added default values for assessments in `analytics_data.update()`) `course_analytics` in `gcourse.py` to fix the generation of progress csvs for i2c. Since language specific i2c is only visible, even though the progress csvs will generated for all languages and since there will be only one entry in the other units and will be cleaned in the progress csv collation logic.
> Changes done so that progress csv get generated for i2c courses

- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/clix-activity-styles.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/css/themes/clix/clix2017.css
- gnowsys-ndf/gnowsys_ndf/ndf/static/ndf/scss/_clix2017.scss
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/activity_player.html
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/header_clix.html
**Issue:**
- Unit names that are part of an activity player are not displayed completely in 1024 x 768 resolution.
- In lower resolutions other navigation buttons overflow from the context of the secondary header.
**Solution:**
- The secondary header (lesson navigation bar) which is part of the activity_player.html template is revamped to display the unit names appropriately and avoid overflow of other navigation buttons.
- Style in the header_clix template is added to keep the font-size consistent.
**Files Changed:**
- activity_player.html           Line No:31
- header_clix.html               Line No:65
- _clix2017.scss
- clix2017.css
**Issue:**
Audio player's width needs to be altered to avoid overlap in certain activities.
**Solution:**
Set the width property varying in accordance to …
> Resolution of CSS Issues in lesson navigation bar and audio player

- gnowsys-ndf/gnowsys_ndf/ndf/models/node.py
- gnowsys-ndf/gnowsys_ndf/ndf/templates/ndf/gin-line-texteditor.html
- gnowsys-ndf/gnowsys_ndf/ndf/templatetags/ndf_tags.py
**Display Replies of buddy name alongwith username for `I2c` course**.
---
+ Issue: On refresh of the page, buddy name not visible on `I2c course`.
+ Fix: Modified a template `gin-line-texteditor.html` to show the replies of buddy name alongwith the logged -in user.
> changes pertaining to display buddy_name alongwith username for replies in I2C course.

- gnowsys-ndf/gnowsys_ndf/ndf/views/methods.py
**Changes related to Sort Unit functionality**
---
Issue : Not able to change the unit order through sort unit functionality.
Fix     : The value(sort order) though saved into db the method `create_gattribute()` is giving out from the cache..So have added logic in case if the attribute `item_sort_list` is changed the cache value for the given key is invalidated. Thus the ndf_tag method `get_attribute_value()` picks from the db and stores it in the cache.
> Changes related to sort unit funtionality
